Repository homarr-labs/homarr, pull requests merged in 2024-08, with the labels that each got.

#912 fix: restrict access to docker containers page to admins
  apps/nextjs/src/app/[locale]/manage/tools/docker/page.tsx
  packages/api/src/router/docker/docker-router.ts
  packages/api/src/router/test/docker/docker-router.spec.ts
Labels: bug

#913 feat: add refresh button to docker containers table
  apps/nextjs/src/app/[locale]/manage/tools/docker/docker-table.tsx
  packages/api/src/router/docker/docker-router.ts
  packages/translation/src/lang/en.ts
Labels: enhancement

#914 feat: add preview to icon picker
  apps/nextjs/src/components/icons/picker/icon-picker.tsx
Labels: enhancement

#915 feat: add support for app url variables
  apps/nextjs/src/app/[locale]/manage/apps/page.tsx
  packages/auth/redirect.ts
  packages/common/package.json
  packages/common/src/app-url/base.ts
  packages/common/src/app-url/client.ts
  packages/common/src/app-url/server.ts
  packages/common/src/client.ts
  packages/common/src/server.ts
  packages/common/src/url.ts
  packages/widgets/src/app/component.tsx
  packages/widgets/src/app/serverData.ts
  packages/widgets/src/app/test/serverData.spec.ts
  pnpm-lock.yaml
Labels: enhancement

#924 fix: ping urls are not reset when restarting
  packages/cron-jobs-core/src/creator.ts
  packages/cron-jobs/src/jobs/ping.ts
  packages/redis/src/lib/channel.ts
Labels: bug

#926 feat: add duplication action for items
  apps/nextjs/src/components/board/items/item-actions.tsx
  apps/nextjs/src/components/board/sections/content.tsx
  packages/translation/src/lang/en.ts
Labels: enhancement

#928 fix: alert that certain fields in user settings are disabled is always shown
  apps/nextjs/src/app/[locale]/manage/users/[userId]/general/page.tsx
Labels: bug

#942 fix: renovate approval run for all pull requests on every pull request change
  .github/workflows/renovate-automatic-approval.yml
Labels: bug

#943 fix: github actor name for automatic approval wrong
  .github/workflows/renovate-automatic-approval.yml
Labels: bug

#949 feat: change visibility in item options based on selected integration kinds
  packages/widgets/src/modals/widget-edit-modal.tsx
  packages/widgets/src/options.ts
Labels: enhancement

#951 feat: add session expiry
  apps/nextjs/src/app/[locale]/_client-providers/session.tsx
  packages/auth/callbacks.ts
  packages/auth/configuration.ts
  packages/auth/env.mjs
  packages/auth/session.ts
  packages/auth/test/callbacks.spec.ts
  turbo.json
Labels: enhancement

#952 fix: redirect url from login not working
  apps/nextjs/src/app/[locale]/auth/login/page.tsx
Labels: bug

#930 feat: add column count and is public options to board creation modal
  apps/nextjs/src/app/[locale]/manage/boards/_components/create-board-button.tsx
  apps/nextjs/src/components/manage/boards/add-board-modal.tsx
  packages/api/src/router/board.ts
  packages/api/src/router/test/board.spec.ts
  packages/translation/src/lang/en.ts
  packages/validation/src/board.ts
Labels: enhancement

#957 fix: wrong id for renovate auto approval
  .github/workflows/renovate-automatic-approval.yml
Labels: bug

#954 feat: add logout redirect url
  apps/nextjs/src/app/[locale]/_client-providers/session.tsx
  apps/nextjs/src/app/[locale]/layout.tsx
  apps/nextjs/src/components/user-avatar-menu.tsx
  packages/auth/env.mjs
  turbo.json
Labels: enhancement

#956 feat: add user setting for home board
  apps/nextjs/src/app/[locale]/manage/users/[userId]/general/_components/_change-home-board.tsx
  apps/nextjs/src/app/[locale]/manage/users/[userId]/general/_components/_profile-language-change.tsx
  apps/nextjs/src/app/[locale]/manage/users/[userId]/general/page.tsx
  packages/api/src/router/user.ts
  packages/translation/src/lang/en.ts
  packages/validation/src/user.ts
Labels: enhancement

#842 feat: add dynamic section
  .gitignore
  apps/nextjs/package.json
  apps/nextjs/src/app/[locale]/boards/(content)/_client.tsx
  apps/nextjs/src/app/[locale]/boards/(content)/_header-actions.tsx
  apps/nextjs/src/app/[locale]/boards/_types.ts
  apps/nextjs/src/components/board/items/item-actions.tsx
  apps/nextjs/src/components/board/items/item-content.tsx
  apps/nextjs/src/components/board/items/item-menu.tsx
  apps/nextjs/src/components/board/sections/category-section.tsx
  apps/nextjs/src/components/board/sections/category/category-actions.ts
  apps/nextjs/src/components/board/sections/category/category-menu-actions.tsx
  apps/nextjs/src/components/board/sections/content.tsx
  apps/nextjs/src/components/board/sections/dynamic-section.tsx
  apps/nextjs/src/components/board/sections/dynamic/dynamic-actions.ts
  apps/nextjs/src/components/board/sections/dynamic/dynamic-menu.tsx
  apps/nextjs/src/components/board/sections/empty-section.tsx
  apps/nextjs/src/components/board/sections/gridstack/gridstack-item.tsx
  apps/nextjs/src/components/board/sections/gridstack/gridstack.tsx
  apps/nextjs/src/components/board/sections/gridstack/init-gridstack.ts
  apps/nextjs/src/components/board/sections/gridstack/use-gridstack.ts
  apps/nextjs/src/components/board/sections/section-actions.tsx
  apps/nextjs/src/components/board/sections/section-context.ts
  apps/nextjs/src/components/board/sections/use-section-items.ts
  apps/nextjs/src/styles/gridstack.scss
  packages/api/src/router/board.ts
  packages/api/src/router/test/board.spec.ts
  packages/db/migrations/mysql/0006_young_micromax.sql
  packages/db/migrations/mysql/meta/0006_snapshot.json
  packages/db/migrations/mysql/meta/_journal.json
  packages/db/migrations/sqlite/0006_windy_doctor_faustus.sql
  packages/db/migrations/sqlite/meta/0006_snapshot.json
  packages/db/migrations/sqlite/meta/_journal.json
  packages/db/schema/mysql.ts
  packages/db/schema/sqlite.ts
  packages/definitions/src/section.ts
  packages/translation/src/lang/en.ts
  packages/validation/src/shared.ts
  pnpm-lock.yaml
Labels: enhancement

#963 feat: add collapse to login screen with cli command for password reset
  apps/nextjs/src/app/[locale]/auth/login/_login-form.tsx
  packages/translation/src/lang/en.ts
Labels: enhancement

#927 feat: add modal to move items on board
  apps/nextjs/src/app/[locale]/widgets/[kind]/_dimension-modal.tsx
  apps/nextjs/src/components/board/items/item-menu.tsx
  apps/nextjs/src/components/board/items/item-move-modal.tsx
  packages/translation/src/lang/en.ts
Labels: enhancement

#986 feat: add hotkeys
  apps/nextjs/src/app/[locale]/boards/(content)/_header-actions.tsx
  apps/nextjs/src/components/user-avatar-menu.tsx
  packages/widgets/src/notebook/notebook.tsx
Labels: enhancement

#774 feat: add media requests widget
  .vscode/settings.json
  packages/api/src/middlewares/integration.ts
  packages/api/src/router/integration/integration-test-connection.ts
  packages/api/src/router/widgets/index.ts
  packages/api/src/router/widgets/media-requests.ts
  packages/cron-jobs/src/index.ts
  packages/cron-jobs/src/jobs/integrations/media-requests.ts
  packages/db/package.json
  packages/db/queries/index.ts
  packages/db/queries/item.ts
  packages/definitions/src/widget.ts
  packages/integrations/src/base/creator.ts
  packages/integrations/src/index.ts
  packages/integrations/src/interfaces/media-requests/media-request.ts
  packages/integrations/src/jellyseerr/jellyseerr-integration.ts
  packages/integrations/src/overseerr/overseerr-integration.ts
  packages/integrations/src/types.ts
  packages/integrations/test/home-assistant.spec.ts
  packages/translation/src/lang/en.ts
  packages/translation/src/type.ts
  packages/widgets/src/clock/component.tsx
  packages/widgets/src/index.tsx
  packages/widgets/src/media-requests/list/component.tsx
  packages/widgets/src/media-requests/list/index.ts
  packages/widgets/src/media-requests/list/serverData.ts
  packages/widgets/src/media-requests/stats/component.module.css
  packages/widgets/src/media-requests/stats/component.tsx
  packages/widgets/src/media-requests/stats/index.ts
  packages/widgets/src/media-requests/stats/serverData.ts
  packages/widgets/src/weather/component.tsx
Labels: widget:media-requests-list, widget:media-request-stats

#1020 fix: improve ping performance
  packages/cron-jobs/src/jobs/ping.ts
Labels: bug

#1024 fix: sonarr testConnectionAsync url
  packages/integrations/src/media-organizer/sonarr/sonarr-integration.ts
Labels: bug

#1025 fix: when removing one item and then adding another one that newly added one can not be moved
  apps/nextjs/src/components/board/sections/gridstack/use-gridstack.ts
Labels: bug
