Repository homarr-labs/homarr, pull requests merged in 2024-12, with the labels that each got.

#1583 fix: fix binary conflicts for linux
  .gitattributes
Labels: bug

#1585 fix: Allow username to be capitalized on basic credentials login
  packages/auth/providers/credentials/authorization/basic-authorization.ts
Labels: bug

#1599 feat: integrate crowdin #1402
  .github/workflows/crowdin-schedule-download.yml
  .github/workflows/crowdin-upload.yml
  crowdin.yml
Labels: enhancement

#1596 feat: pretty-print-error to print errors in console
  package.json
  packages/request-handler/package.json
  packages/request-handler/src/lib/cached-request-integration-job-handler.ts
  patches/pretty-print-error.patch
  pnpm-lock.yaml
Labels: enhancement

#1570 feat: add context specific search and actions
  apps/nextjs/src/app/[locale]/layout.tsx
  packages/common/src/app-url/client.ts
  packages/spotlight/src/components/actions/group-actions.tsx
  packages/spotlight/src/components/spotlight.tsx
  packages/spotlight/src/index.ts
  packages/spotlight/src/lib/mode.ts
  packages/spotlight/src/modes/command/context-specific-group.tsx
  packages/spotlight/src/modes/command/global-group.tsx
  packages/spotlight/src/modes/command/index.tsx
  packages/spotlight/src/modes/home/context-specific-group.tsx
  packages/spotlight/src/modes/home/context.tsx
  packages/spotlight/src/modes/home/index.tsx
  packages/spotlight/src/modes/index.tsx
  packages/translation/src/lang/en.json
  packages/widgets/src/app/component.tsx
  packages/widgets/src/bookmarks/component.tsx
  packages/widgets/src/smart-home/entity-state/component.tsx
  packages/widgets/src/smart-home/execute-automation/component.tsx
Labels: enhancement

#1541 feat: add dashdot integration
  .vscode/settings.json
  package.json
  packages/api/src/router/widgets/health-monitoring.ts
  packages/definitions/src/integration.ts
  packages/integrations/src/base/creator.ts
  packages/integrations/src/dashdot/dashdot-integration.ts
  packages/redis/src/lib/channel.ts
  packages/widgets/src/health-monitoring/component.tsx
  packages/widgets/src/health-monitoring/index.ts
Labels: enhancement

#1632 ci: add auto-merge after crowdin download and automatic approval
  .github/workflows/automatic-approval.yml
  .github/workflows/crowdin-schedule-download.yml
  crowdin.yml
Labels: enhancement

#1645 fix: styles for light mode
  apps/nextjs/src/app/[locale]/manage/_components/hero-banner.module.css
  apps/nextjs/src/app/[locale]/manage/_components/hero-banner.tsx
  apps/nextjs/src/app/[locale]/manage/apps/page.tsx
  apps/nextjs/src/app/[locale]/manage/boards/page.tsx
  apps/nextjs/src/app/[locale]/manage/integrations/_components/secrets/integration-secret-card.tsx
  apps/nextjs/src/app/[locale]/manage/search-engines/page.tsx
  apps/nextjs/src/app/[locale]/manage/tools/tasks/_components/jobs-list.tsx
  apps/nextjs/src/app/[locale]/manage/users/create/_components/create-user-stepper.tsx
  apps/nextjs/src/components/icons/picker/icon-picker.tsx
Labels: enhancement

#1626 feat: add update indicator
  apps/nextjs/src/components/layout/header/user.tsx
  apps/nextjs/src/components/user-avatar-menu.tsx
  package.json
  packages/api/src/root.ts
  packages/api/src/router/update-checker.ts
  packages/cron-jobs/package.json
  packages/cron-jobs/src/index.ts
  packages/cron-jobs/src/jobs/update-checker.ts
  packages/redis/src/index.ts
  packages/request-handler/package.json
  packages/request-handler/src/update-checker.ts
  packages/translation/src/lang/en.json
  pnpm-lock.yaml
Labels: enhancement

#1655 feat: add error page for docker tools page
  apps/nextjs/src/app/[locale]/manage/tools/docker/error.tsx
  packages/api/src/router/docker/docker-router.ts
  packages/translation/src/lang/en.json
  packages/widgets/src/errors/base-component.tsx
Labels: enhancement

#1660 fix: trpc error at least one integration
  apps/nextjs/src/components/board/items/item-content.tsx
  packages/widgets/src/dns-hole/controls/component.tsx
  packages/widgets/src/dns-hole/summary/component.tsx
  packages/widgets/src/downloads/component.tsx
  packages/widgets/src/health-monitoring/component.tsx
  packages/widgets/src/indexer-manager/component.tsx
  packages/widgets/src/media-requests/list/component.tsx
  packages/widgets/src/media-requests/stats/component.tsx
  packages/widgets/src/smart-home/entity-state/component.tsx
Labels: bug

#1661 fix: auto-merge for crowdin download pull request not working
  .github/workflows/crowdin-schedule-download.yml
Labels: bug

#1664 fix: auto-merge crowdin pr not working
  .github/workflows/crowdin-schedule-download.yml
Labels: bug

#1662 docs: create SECURITY.md
  SECURITY.md
Labels: documentation

#1666 fix: icon picker keyboard interactions
  apps/nextjs/src/components/icons/picker/icon-picker.module.css
  apps/nextjs/src/components/icons/picker/icon-picker.tsx
Labels: bug

#1657 feat: add tdarr integration
  packages/api/src/router/widgets/index.ts
  packages/api/src/router/widgets/media-transcoding.ts
  packages/cron-jobs/src/index.ts
  packages/cron-jobs/src/jobs/integrations/media-transcoding.ts
  packages/definitions/src/integration.ts
  packages/definitions/src/widget.ts
  packages/integrations/src/base/creator.ts
  packages/integrations/src/index.ts
  packages/integrations/src/interfaces/media-transcoding/queue.ts
  packages/integrations/src/interfaces/media-transcoding/statistics.ts
  packages/integrations/src/interfaces/media-transcoding/workers.ts
  packages/integrations/src/media-transcoding/tdarr-integration.ts
  packages/integrations/src/media-transcoding/tdarr-validation-schemas.ts
  packages/old-import/src/mappers/map-integration.ts
  packages/old-import/src/widgets/definitions/index.ts
  packages/old-import/src/widgets/options.ts
  packages/request-handler/src/media-transcoding.ts
  packages/translation/src/lang/en.json
  packages/widgets/src/index.tsx
  packages/widgets/src/media-transcoding/component.tsx
  packages/widgets/src/media-transcoding/health-check-status.tsx
  packages/widgets/src/media-transcoding/index.ts
  packages/widgets/src/media-transcoding/panels/queue.panel.tsx
  packages/widgets/src/media-transcoding/panels/statistics.panel.tsx
  packages/widgets/src/media-transcoding/panels/workers.panel.tsx
Labels: enhancement

#1671 feat: add not found pages for boards
  apps/nextjs/src/app/[locale]/(home)/(board)/layout.tsx
  apps/nextjs/src/app/[locale]/(home)/(board)/page.tsx
  apps/nextjs/src/app/[locale]/(home)/not-found.tsx
  apps/nextjs/src/app/[locale]/(home-board)/layout.tsx
  apps/nextjs/src/app/[locale]/boards/(content)/[name]/(board)/_definition.tsx
  apps/nextjs/src/app/[locale]/boards/(content)/[name]/(board)/layout.tsx
  apps/nextjs/src/app/[locale]/boards/(content)/[name]/(board)/page.tsx
  apps/nextjs/src/app/[locale]/boards/(content)/[name]/not-found.tsx
  apps/nextjs/src/app/[locale]/boards/(content)/not-found.tsx
  apps/nextjs/src/components/board/not-found.tsx
  packages/translation/src/lang/en.json
Labels: enhancement

#1684 docs: update license to apache 2.0
  LICENSE
Labels: documentation

#1679 ci: adjust release pipeline for semver releases
  .github/workflows/deployment-docker-image.yml
  .github/workflows/deployment-weekly-release.yml
  .releaserc.json
  package.json
  pnpm-lock.yaml
  tooling/semver/package.json
  tooling/semver/release.config.cjs
Labels: enhancement

#1687 fix: change docker concurrency group to allow multiple deployments to different branches
  .github/workflows/deployment-docker-image.yml
Labels: bug

#1706 fix: about version reads nextjs package-json
  apps/nextjs/src/versions/package-reader.ts
Labels: bug

#1711 fix: permission required for home page
  apps/nextjs/src/components/layout/header/user.tsx
Labels: bug

#1714 fix: jellyfin integration does not allow username password auth
  packages/integrations/src/base/integration.ts
  packages/integrations/src/jellyfin/jellyfin-integration.ts
Labels: bug

#1723 fix: allow additional file-type for oldmarr import
  apps/nextjs/src/app/[locale]/init/_steps/import/import-dropzone.tsx
Labels: bug

#1724 fix: update of dev branch has no credentials
  .github/workflows/deployment-docker-image.yml
Labels: bug

#1725 fix: about version is one behind because of missing package-json update in deploy
  .github/workflows/deployment-docker-image.yml
Labels: bug

#1730 fix: always require db-user and password for mysql
  apps/nextjs/next.config.mjs
  apps/nextjs/src/env.mjs
  packages/db/configs/mysql.config.ts
  packages/db/configs/sqlite.config.ts
  packages/db/driver.ts
  packages/db/env.mjs
  packages/db/migrations/mysql/migrate.ts
  packages/db/migrations/sqlite/migrate.ts
  packages/db/package.json
  pnpm-lock.yaml
Labels: bug

#1745 docs: update crowdin badge to new translation project
  docs/README.md
Labels: documentation

#1750 fix: copy media link
  apps/nextjs/src/app/[locale]/manage/medias/_actions/copy-media.tsx
Labels: bug

#1765 fix(icons): local icon repository does not work with medias
  packages/api/package.json
  packages/api/src/router/medias/media-router.ts
  packages/icons/package.json
  packages/icons/src/local.ts
  packages/icons/src/repositories/local.icon-repository.ts
  pnpm-lock.yaml
Labels: bug

#1763 fix(auth): oidc redirect does not respect https protocol
  .github/workflows/deployment-docker-image.yml
  nginx.conf
  packages/auth/providers/oidc/oidc-provider.ts
  packages/auth/redirect.ts
  packages/common/src/url.ts
Labels: bug

#1764 fix(onboard): missing admin permission assignment for external group
  packages/api/src/router/group.ts
Labels: bug

#1770 fix(board): tiles order not respected on firefox
  apps/nextjs/src/components/board/sections/content.tsx
Labels: bug

#1769 fix(board): item background and border overridden by mantine card styles
  apps/nextjs/src/components/board/sections/item.module.css
Labels: bug

#1784 fix: oldmarr import user casing wrong
  packages/old-import/src/mappers/map-user.ts
Labels: bug

#1792 fix(health-monitoring): add months to uptime, fix status update
  packages/translation/src/lang/en.json
  packages/widgets/src/health-monitoring/component.tsx
Labels: bug

#1801 feat(widget): add minecraft server status widget
  packages/api/src/router/widgets/index.ts
  packages/api/src/router/widgets/minecraft.ts
  packages/cron-jobs/src/index.ts
  packages/cron-jobs/src/jobs/minecraft-server-status.ts
  packages/definitions/src/widget.ts
  packages/redis/src/index.ts
  packages/redis/src/lib/channel.ts
  packages/request-handler/src/lib/cached-widget-request-handler.ts
  packages/request-handler/src/minecraft-server-status.ts
  packages/translation/src/lang/en.json
  packages/widgets/src/index.tsx
  packages/widgets/src/minecraft/server-status/component.tsx
  packages/widgets/src/minecraft/server-status/index.ts
Labels: enhancement

#1811 feat: add request media
  packages/api/src/router/search-engine/search-engine-router.ts
  packages/definitions/src/docs/homarr-docs-sitemap.ts
  packages/integrations/src/base/searchable-integration.ts
  packages/integrations/src/overseerr/overseerr-integration.ts
  packages/modals-collection/src/index.ts
  packages/modals-collection/src/search-engines/index.ts
  packages/modals-collection/src/search-engines/request-media-modal.tsx
  packages/spotlight/src/components/actions/children-actions.tsx
  packages/spotlight/src/components/actions/items/children-action-item.tsx
  packages/spotlight/src/components/spotlight.tsx
  packages/spotlight/src/lib/children.ts
  packages/spotlight/src/modes/external/search-engines-search-group.tsx
  packages/translation/src/lang/en.json
  packages/validation/src/common.ts
Labels: enhancement

#1809 fix(docker): replace anonymous docker volume with env variable for encrypting secrets
  .env.example
  Dockerfile
  apps/nextjs/next.config.mjs
  e2e/shared/create-homarr-container.ts
  packages/auth/env.mjs
  packages/common/env.mjs
  packages/common/package.json
  packages/common/src/encryption.ts
  scripts/generateRandomSecureKey.js
  scripts/run.sh
  turbo.json
Labels: bug

#1759 feat(docker): add support for pgid and puid env variables
  Dockerfile
  scripts/entrypoint.sh
  scripts/run.sh
Labels: bug, enhancement

#1816 feat(integration): add search engine creation
  .vscode/settings.json
  apps/nextjs/src/app/[locale]/manage/integrations/new/_integration-new-form.tsx
  packages/api/src/router/integration/integration-router.ts
  packages/api/src/router/test/integration/integration-router.spec.ts
  packages/db/migrations/mysql/0018_mighty_shaman.sql
  packages/db/migrations/mysql/meta/0018_snapshot.json
  packages/db/migrations/mysql/meta/_journal.json
  packages/db/migrations/sqlite/0018_cheerful_tattoo.sql
  packages/db/migrations/sqlite/meta/0018_snapshot.json
  packages/db/migrations/sqlite/meta/_journal.json
  packages/db/schema/mysql.ts
  packages/db/schema/sqlite.ts
  packages/icons/index.ts
  packages/icons/src/auto-icon-searcher.ts
  packages/translation/src/lang/en.json
  packages/validation/src/integration.ts
Labels: enhancement
