Repository homarr-labs/homarr, pull requests merged in 2024-10, with the labels that each got.

#1149 feat: add member sync between groups of ldap and homarr
  packages/auth/providers/credentials/authorization/ldap-authorization.ts
  packages/auth/providers/test/ldap-authorization.spec.ts
Labels: enhancement

#1217 fix: it was possible to go to the create user page when credentials login disabled
  apps/nextjs/src/app/[locale]/manage/users/_components/user-list.tsx
  apps/nextjs/src/app/[locale]/manage/users/create/page.tsx
  apps/nextjs/src/app/[locale]/manage/users/page.tsx
Labels: bug

#1218 fix: email verified check is in a newline in users table
  apps/nextjs/src/app/[locale]/manage/users/_components/user-list.tsx
  packages/translation/src/lang/en.ts
Labels: bug

#1202 feat(docker): add encryption key generation for integration secrets
  Dockerfile
  packages/common/package.json
  packages/common/src/encryption.ts
  pnpm-lock.yaml
  scripts/generateEncryptionKey.js
  scripts/run.sh
Labels: enhancement

#1230 fix: new sections without add and change listeners
  apps/nextjs/src/components/board/sections/gridstack/use-gridstack.ts
Labels: bug

#1232 fix: confirm not selected by default in confirm modal
  packages/modals/src/confirm-modal.tsx
Labels: bug

#1200 feat(spotlight): add support for custom search-engines
  apps/nextjs/src/app/[locale]/manage/apps/page.tsx
  apps/nextjs/src/app/[locale]/manage/layout.tsx
  apps/nextjs/src/app/[locale]/manage/search-engines/_form.tsx
  apps/nextjs/src/app/[locale]/manage/search-engines/_search-engine-delete-button.tsx
  apps/nextjs/src/app/[locale]/manage/search-engines/edit/[id]/_search-engine-edit-form.tsx
  apps/nextjs/src/app/[locale]/manage/search-engines/edit/[id]/page.tsx
  apps/nextjs/src/app/[locale]/manage/search-engines/new/_search-engine-new-form.tsx
  apps/nextjs/src/app/[locale]/manage/search-engines/new/page.tsx
  apps/nextjs/src/app/[locale]/manage/search-engines/page.tsx
  packages/api/src/root.ts
  packages/api/src/router/app.ts
  packages/api/src/router/group.ts
  packages/api/src/router/search-engine/search-engine-router.ts
  packages/db/migrations/mysql/0008_far_lifeguard.sql
  packages/db/migrations/mysql/meta/0008_snapshot.json
  packages/db/migrations/mysql/meta/_journal.json
  packages/db/migrations/sqlite/0008_third_thor.sql
  packages/db/migrations/sqlite/meta/0008_snapshot.json
  packages/db/migrations/sqlite/meta/_journal.json
  packages/db/schema/mysql.ts
  packages/db/schema/sqlite.ts
  packages/spotlight/src/components/actions/group-actions.tsx
  packages/spotlight/src/components/actions/groups/action-group.tsx
  packages/spotlight/src/components/spotlight.tsx
  packages/spotlight/src/lib/group.ts
  packages/spotlight/src/modes/external/search-engines-search-group.tsx
  packages/spotlight/src/modes/page/pages-search-group.tsx
  packages/translation/src/lang/en.ts
  packages/validation/src/app.ts
  packages/validation/src/common.ts
  packages/validation/src/form/i18n.ts
  packages/validation/src/group.ts
  packages/validation/src/index.ts
  packages/validation/src/search-engine.ts
Labels: enhancement

#1236 chore: revert base image to 20.17.0 alpine
  Dockerfile
Labels: bug

#991 feat: add api keys
  apps/nextjs/src/app/[locale]/manage/tools/api/components/api-keys.tsx
  apps/nextjs/src/app/[locale]/manage/tools/api/components/copy-api-key-modal.tsx
  apps/nextjs/src/app/[locale]/manage/tools/api/components/swagger-ui.tsx
  apps/nextjs/src/app/[locale]/manage/tools/api/page.tsx
  apps/nextjs/src/app/[locale]/manage/tools/api/swagger-ui.css
  apps/nextjs/src/app/api/[...trpc]/route.ts
  packages/api/src/open-api.ts
  packages/api/src/root.ts
  packages/api/src/router/apiKeys.ts
  packages/api/src/router/app.ts
  packages/api/src/router/user.ts
  packages/auth/callbacks.ts
  packages/auth/server.ts
  packages/db/migrations/mysql/0009_wakeful_tenebrous.sql
  packages/db/migrations/mysql/meta/0009_snapshot.json
  packages/db/migrations/mysql/meta/_journal.json
  packages/db/migrations/sqlite/0009_stale_roulette.sql
  packages/db/migrations/sqlite/meta/0009_snapshot.json
  packages/db/migrations/sqlite/meta/_journal.json
  packages/db/schema/mysql.ts
  packages/db/schema/sqlite.ts
  packages/translation/src/lang/en.ts
Labels: enhancement

#1246 fix: rtl common translation unnecessary
  apps/nextjs/src/app/[locale]/_client-providers/mantine.tsx
  apps/nextjs/src/app/[locale]/layout.tsx
  apps/nextjs/src/app/[locale]/manage/search-engines/page.tsx
  apps/nextjs/src/app/[locale]/manage/users/groups/[id]/members/page.tsx
  apps/nextjs/src/app/[locale]/manage/users/groups/page.tsx
  apps/nextjs/src/components/layout/header/search.tsx
  packages/spotlight/src/components/spotlight.tsx
  packages/translation/src/lang/en.ts
  packages/widgets/src/app/component.tsx
  packages/widgets/src/dns-hole/summary/component.tsx
  packages/widgets/src/downloads/component.tsx
  packages/widgets/src/media-requests/stats/component.tsx
  packages/widgets/src/weather/icon.tsx
Labels: bug

#1219 fix: permissions not restricted for certain management pages / actions
  apps/nextjs/src/app/[locale]/manage/boards/page.tsx
  apps/nextjs/src/app/[locale]/manage/integrations/edit/[id]/page.tsx
  apps/nextjs/src/app/[locale]/manage/integrations/new/page.tsx
  apps/nextjs/src/app/[locale]/manage/integrations/page.tsx
  apps/nextjs/src/app/[locale]/manage/layout.tsx
  apps/nextjs/src/app/[locale]/manage/page.tsx
  apps/nextjs/src/app/[locale]/manage/tools/api/page.tsx
  apps/nextjs/src/app/[locale]/manage/tools/logs/page.tsx
  apps/nextjs/src/app/[locale]/manage/tools/tasks/page.tsx
  apps/nextjs/src/app/[locale]/manage/users/create/page.tsx
  apps/nextjs/src/app/[locale]/manage/users/groups/page.tsx
  apps/nextjs/src/app/[locale]/manage/users/invites/page.tsx
  apps/nextjs/src/app/[locale]/manage/users/page.tsx
  packages/api/src/router/app.ts
  packages/api/src/router/cron-jobs.ts
  packages/api/src/router/group.ts
  packages/api/src/router/home.ts
  packages/api/src/router/integration/integration-router.ts
  packages/api/src/router/log.ts
  packages/api/src/router/test/app.spec.ts
  packages/api/src/router/test/group.spec.ts
  packages/api/src/router/test/user.spec.ts
  packages/api/src/router/user.ts
  packages/auth/permissions/integration-permissions.ts
  packages/auth/test/callbacks.spec.ts
  packages/spotlight/src/modes/page/pages-search-group.tsx
  packages/translation/src/lang/en.ts
  vitest.config.mts
Labels: bug

#1223 refactor: replace signIn callback with signIn event, adjust getUserByEmail in adapter to check provider
  apps/nextjs/src/app/[locale]/auth/login/_login-form.tsx
  apps/nextjs/src/app/api/auth/[...nextauth]/route.ts
  packages/auth/adapter.ts
  packages/auth/callbacks.ts
  packages/auth/configuration.ts
  packages/auth/env.mjs
  packages/auth/events.ts
  packages/auth/index.ts
  packages/auth/next.ts
  packages/auth/providers/credentials/authorization/ldap-authorization.ts
  packages/auth/providers/credentials/credentials-provider.ts
  packages/auth/providers/test/basic-authorization.spec.ts
  packages/auth/providers/test/ldap-authorization.spec.ts
  packages/auth/session.ts
  packages/auth/test/adapter.spec.ts
  packages/auth/test/callbacks.spec.ts
  packages/auth/test/events.spec.ts
  packages/validation/src/user.ts
  turbo.json
Labels: enhancement

#1267 fix: groups can be created with empty names
  packages/validation/src/group.ts
Labels: bug

#1284 fix: credentials auth not working
  packages/auth/configuration.ts
Labels: bug

#1277 feat: user setting ping icons
  apps/nextjs/src/app/[locale]/manage/users/[userId]/general/_components/_ping-icons-enabled.tsx
  apps/nextjs/src/app/[locale]/manage/users/[userId]/general/page.tsx
  packages/api/src/router/test/user.spec.ts
  packages/api/src/router/user.ts
  packages/db/migrations/mysql/0011_freezing_banshee.sql
  packages/db/migrations/mysql/meta/0011_snapshot.json
  packages/db/migrations/mysql/meta/_journal.json
  packages/db/migrations/sqlite/0011_classy_angel.sql
  packages/db/migrations/sqlite/meta/0011_snapshot.json
  packages/db/migrations/sqlite/meta/_journal.json
  packages/db/package.json
  packages/db/schema/mysql.ts
  packages/db/schema/sqlite.ts
  packages/translation/src/lang/en.ts
  packages/validation/src/user.ts
  packages/widgets/src/app/component.tsx
  packages/widgets/src/app/ping/ping-dot.tsx
  packages/widgets/src/app/ping/ping-indicator.tsx
Labels: enhancement

#1300 fix: integration actions hidden for full access users
  apps/nextjs/src/app/[locale]/manage/integrations/page.tsx
Labels: bug

#1296 feat: populate integration name for new integrations automatically
  apps/nextjs/src/app/[locale]/manage/integrations/new/_integration-new-form.tsx
Labels: enhancement

#1297 feat: add notes for creation of apps and integrations in widget edit modal
  packages/translation/src/lang/en.ts
  packages/widgets/src/_inputs/widget-app-input.tsx
  packages/widgets/src/options.ts
  packages/widgets/src/widget-integration-select.tsx
Labels: enhancement

#1299 fix: prevent flickering by removing auto color scheme and default background color
  apps/nextjs/src/app/[locale]/_client-providers/mantine.tsx
  apps/nextjs/src/app/[locale]/layout.tsx
  packages/auth/callbacks.ts
  packages/db/schema/mysql.ts
  packages/db/schema/sqlite.ts
  packages/definitions/src/user.ts
Labels: bug

#1310 fix: inconsistent session cookie
  .env.example
  packages/auth/configuration.ts
Labels: bug

#1309 feat: add manifest
  apps/nextjs/public/images/pwa/192.maskable.png
  apps/nextjs/public/images/pwa/512.maskable.png
  apps/nextjs/src/app/manifest.ts
Labels: enhancement

#1308 feat: improve metadata
  apps/nextjs/src/app/[locale]/boards/(content)/_creator.tsx
  apps/nextjs/src/app/[locale]/layout.tsx
Labels: enhancement

#1210 fix: add subscription to health monitoring widget
  packages/api/src/router/widgets/health-monitoring.ts
  packages/translation/src/lang/en.ts
  packages/widgets/src/health-monitoring/component.tsx
Labels: bug

#1328 fix: local websocket url wrong
  apps/nextjs/src/app/[locale]/_client-providers/trpc.tsx
Labels: bug

#1329 fix: color scheme manager should use cookie and not session value
  apps/nextjs/src/app/[locale]/_client-providers/mantine.tsx
Labels: bug

#1335 fix: missing migration for default colorscheme change
  packages/db/migrations/mysql/0012_abnormal_wendell_vaughn.sql
  packages/db/migrations/mysql/meta/0012_snapshot.json
  packages/db/migrations/mysql/meta/_journal.json
  packages/db/migrations/sqlite/0012_ambiguous_black_panther.sql
  packages/db/migrations/sqlite/meta/0012_snapshot.json
  packages/db/migrations/sqlite/meta/_journal.json
Labels: bug

#1247 feat: RTL option to RSS widget
  packages/old-import/src/widgets/definitions/rss.ts
  packages/old-import/src/widgets/options.ts
  packages/translation/src/lang/en.ts
  packages/widgets/src/rssFeed/component.tsx
  packages/widgets/src/rssFeed/index.ts
Labels: widget:rss-feed

#1322 feat: add everyone group
  .github/renovate.json5
  apps/nextjs/src/app/[locale]/manage/layout.tsx
  apps/nextjs/src/app/[locale]/manage/users/groups/[id]/_rename-group-form.tsx
  apps/nextjs/src/app/[locale]/manage/users/groups/[id]/_reserved-group-alert.tsx
  apps/nextjs/src/app/[locale]/manage/users/groups/[id]/members/page.tsx
  apps/nextjs/src/app/[locale]/manage/users/groups/[id]/page.tsx
  apps/tasks/package.json
  apps/tasks/src/main.ts
  apps/tasks/src/seed-server-settings.ts
  apps/websocket/package.json
  packages/api/src/router/group.ts
  packages/auth/events.ts
  packages/auth/test/events.spec.ts
  packages/db/migrations/mysql/0013_youthful_vulture.sql
  packages/db/migrations/mysql/meta/0013_snapshot.json
  packages/db/migrations/mysql/meta/_journal.json
  packages/db/migrations/mysql/migrate.ts
  packages/db/migrations/run-seed.ts
  packages/db/migrations/seed.ts
  packages/db/migrations/sqlite/0013_faithful_hex.sql
  packages/db/migrations/sqlite/meta/0013_snapshot.json
  packages/db/migrations/sqlite/meta/_journal.json
  packages/db/migrations/sqlite/migrate.ts
  packages/db/package.json
  packages/db/schema/mysql.ts
  packages/db/schema/sqlite.ts
  packages/definitions/package.json
  packages/definitions/src/docs/codegen.ts
  packages/definitions/src/docs/homarr-docs-sitemap.ts
  packages/definitions/src/docs/index.ts
  packages/definitions/src/group.ts
  packages/definitions/src/index.ts
  packages/spotlight/src/modes/index.tsx
  packages/translation/src/lang/en.ts
  packages/validation/src/group.ts
  packages/widgets/src/video/component.tsx
  pnpm-lock.yaml
  tooling/eslint/base.js
Labels: enhancement

#1342 feat: plex integration
  packages/integrations/package.json
  packages/integrations/src/base/creator.ts
  packages/integrations/src/index.ts
  packages/integrations/src/plex/interface.ts
  packages/integrations/src/plex/plex-integration.ts
  packages/widgets/src/media-server/index.ts
  pnpm-lock.yaml
Labels: enhancement

#1365 fix: docker build not working
  Dockerfile
  package.json
Labels: bug

#1337 feat: add media management
  apps/nextjs/src/app/[locale]/manage/layout.tsx
  apps/nextjs/src/app/[locale]/manage/medias/_actions/copy-media.tsx
  apps/nextjs/src/app/[locale]/manage/medias/_actions/delete-media.tsx
  apps/nextjs/src/app/[locale]/manage/medias/_actions/show-all.tsx
  apps/nextjs/src/app/[locale]/manage/medias/_actions/upload-media.tsx
  apps/nextjs/src/app/[locale]/manage/medias/page.tsx
  apps/nextjs/src/app/api/user-medias/[id]/route.ts
  packages/api/src/root.ts
  packages/api/src/router/medias/media-router.ts
  packages/db/migrations/mysql/0014_bizarre_red_shift.sql
  packages/db/migrations/mysql/meta/0014_snapshot.json
  packages/db/migrations/mysql/meta/_journal.json
  packages/db/migrations/sqlite/0014_colorful_cargill.sql
  packages/db/migrations/sqlite/meta/0014_snapshot.json
  packages/db/migrations/sqlite/meta/_journal.json
  packages/db/schema/mysql.ts
  packages/db/schema/sqlite.ts
  packages/db/test/schema.spec.ts
  packages/spotlight/src/modes/page/pages-search-group.tsx
  packages/translation/src/lang/en.ts
  packages/validation/src/index.ts
  packages/validation/src/media.ts
Labels: enhancement
