Repository homarr-labs/homarr, pull requests merged in 2024-09, with the labels that each got.

#965 feat: Prowlarr integration
  apps/nextjs/package.json
  apps/tasks/package.json
  apps/websocket/package.json
  package.json
  packages/analytics/package.json
  packages/api/package.json
  packages/auth/package.json
  packages/cli/package.json
  packages/common/package.json
  packages/cron-job-runner/package.json
  packages/cron-job-status/package.json
  packages/cron-jobs-core/package.json
  packages/cron-jobs/package.json
  packages/db/package.json
  packages/definitions/package.json
  packages/definitions/src/integration.ts
  packages/form/package.json
  packages/icons/package.json
  packages/integrations/package.json
  packages/integrations/src/base/creator.ts
  packages/integrations/src/interfaces/indexer-manager/indexer.ts
  packages/integrations/src/prowlarr/prowlarr-integration.ts
  packages/integrations/src/prowlarr/prowlarr-types.ts
  packages/log/package.json
  packages/modals/package.json
  packages/notifications/package.json
  packages/ping/package.json
  packages/redis/package.json
  packages/server-settings/package.json
  packages/spotlight/package.json
  packages/translation/package.json
  packages/ui/package.json
  packages/validation/package.json
  packages/widgets/package.json
Labels: enhancement

#987 feat: add colorscheme to user in db
  apps/nextjs/src/app/[locale]/_client-providers/mantine.tsx
  apps/nextjs/src/app/[locale]/layout.tsx
  packages/api/src/router/test/board.spec.ts
  packages/api/src/router/test/docker/docker-router.spec.ts
  packages/api/src/router/test/group.spec.ts
  packages/api/src/router/test/integration/integration-router.spec.ts
  packages/api/src/router/test/invite.spec.ts
  packages/api/src/router/test/serverSettings.spec.ts
  packages/api/src/router/test/user.spec.ts
  packages/api/src/router/user.ts
  packages/auth/callbacks.ts
  packages/auth/index.ts
  packages/auth/permissions/test/board-permissions.spec.ts
  packages/auth/permissions/test/integration-permissions.spec.ts
  packages/auth/permissions/test/integration-query-permissions.spec.ts
  packages/auth/session.ts
  packages/auth/test/callbacks.spec.ts
  packages/db/migrations/mysql/0007_boring_nocturne.sql
  packages/db/migrations/mysql/meta/0007_snapshot.json
  packages/db/migrations/mysql/meta/_journal.json
  packages/db/migrations/sqlite/0007_known_ultragirl.sql
  packages/db/migrations/sqlite/meta/0007_snapshot.json
  packages/db/migrations/sqlite/meta/_journal.json
  packages/db/schema/mysql.ts
  packages/db/schema/sqlite.ts
  packages/definitions/src/index.ts
  packages/definitions/src/user.ts
  packages/validation/src/user.ts
Labels: enhancement

#1071 fix: dns-hole controls display on safari
  packages/widgets/src/dns-hole/controls/component.tsx
Labels: bug

#1072 fix: websocket url is always localhost
  apps/nextjs/src/app/[locale]/_client-providers/trpc.tsx
  apps/nextjs/src/app/[locale]/manage/tools/logs/client.tsx
  apps/nextjs/src/app/[locale]/manage/tools/logs/page.tsx
  apps/nextjs/src/app/[locale]/manage/tools/logs/terminal.tsx
Labels: bug

#1053 feat: radarr integration
  packages/cron-jobs/src/jobs/integrations/media-organizer.ts
  packages/integrations/src/base/creator.ts
  packages/integrations/src/index.ts
  packages/integrations/src/media-organizer/radarr/radarr-integration.ts
Labels: enhancement

#1057 feat: indexer manager widget
  packages/api/src/router/widgets/index.ts
  packages/api/src/router/widgets/indexer-manager.ts
  packages/cron-jobs/src/index.ts
  packages/cron-jobs/src/jobs/integrations/indexer-manager.ts
  packages/definitions/src/widget.ts
  packages/integrations/src/index.ts
  packages/integrations/src/prowlarr/prowlarr-integration.ts
  packages/integrations/src/types.ts
  packages/old-import/src/widgets/definitions/index.ts
  packages/old-import/src/widgets/options.ts
  packages/translation/src/lang/en.ts
  packages/widgets/src/index.tsx
  packages/widgets/src/indexer-manager/component.tsx
  packages/widgets/src/indexer-manager/index.ts
  packages/widgets/src/indexer-manager/serverData.ts
Labels: enhancement

#1101 fix: hard to move iframe widget #1075
  packages/widgets/src/iframe/component.tsx
Labels: bug

#1123 fix: workflow inputs and docker push
  .github/workflows/deployment-docker-image.yml
Labels: bug

#1124 fix: node cache cleanup error
  .github/workflows/deployment-docker-image.yml
Labels: enhancement

#1073 feat: add nginx proxy
  Dockerfile
  apps/nextjs/src/app/[locale]/_client-providers/trpc.tsx
  nginx.conf
  scripts/run.sh
Labels: enhancement

#1137 fix: db port validation for env variable wrong
  apps/nextjs/src/env.mjs
Labels: bug

#1138 fix: mysql migration not working
  packages/db/migrations/mysql/0004_noisy_giant_girl.sql
  packages/db/migrations/mysql/0006_young_micromax.sql
  packages/db/migrations/mysql/meta/0004_snapshot.json
  packages/db/migrations/mysql/meta/0005_snapshot.json
  packages/db/migrations/mysql/meta/0006_snapshot.json
  packages/db/migrations/mysql/meta/0007_snapshot.json
  packages/db/migrations/sqlite/meta/0004_snapshot.json
  packages/db/migrations/sqlite/meta/0005_snapshot.json
  packages/db/migrations/sqlite/meta/0006_snapshot.json
  packages/db/migrations/sqlite/meta/0007_snapshot.json
  packages/db/package.json
  packages/db/schema/mysql.ts
  packages/db/test/mysql-migration.spec.ts
  pnpm-lock.yaml
Labels: bug

#1143 refactor: use suspense query instead of serverdata for app widget
  packages/translation/src/lang/en.ts
  packages/widgets/src/app/component.tsx
  packages/widgets/src/app/index.ts
  packages/widgets/src/app/ping/ping-dot.tsx
  packages/widgets/src/app/ping/ping-indicator.tsx
  packages/widgets/src/app/serverData.ts
  packages/widgets/src/app/test/serverData.spec.ts
  packages/widgets/src/definition.ts
  packages/widgets/src/errors/component.tsx
  packages/widgets/src/index.tsx
  packages/widgets/src/server/runner.tsx
Labels: enhancement

#1161 fix: insert limit of sqlite is smaller than amount of icons
  packages/cron-jobs/src/jobs/icons-updater.ts
Labels: bug

#1160 ci: fix issue with pnpm installation
  Dockerfile
  development/docker-run.cmd
Labels: bug

#1179 feat: add env variable to disable db migrations on startup
  scripts/run.sh
Labels: enhancement

#1168 fix: issue with color scheme in layout
  apps/nextjs/src/app/[locale]/_client-providers/mantine.tsx
  apps/nextjs/src/app/[locale]/layout.tsx
  packages/auth/callbacks.ts
  packages/auth/configuration.ts
  packages/auth/test/callbacks.spec.ts
  packages/common/src/cookie.ts
Labels: bug

#1187 feat: add healthchecks
  .gitignore
  apps/nextjs/package.json
  apps/nextjs/src/app/api/health/live/route.ts
  apps/nextjs/src/app/api/health/ready/route.ts
  packages/redis/src/index.ts
  packages/redis/src/lib/channel.ts
  pnpm-lock.yaml
Labels: enhancement

#1199 fix(spotlight): x button not clickable, help links open in current tab, bad screen usage on mobile
  packages/spotlight/src/components/spotlight.tsx
  packages/spotlight/src/modes/index.tsx
Labels: bug

#1142 feat: OMV integration & health monitoring widget
  packages/api/src/router/widgets/health-monitoring.ts
  packages/api/src/router/widgets/index.ts
  packages/cron-jobs/src/index.ts
  packages/cron-jobs/src/jobs/integrations/health-monitoring.ts
  packages/definitions/src/integration.ts
  packages/definitions/src/widget.ts
  packages/integrations/src/base/creator.ts
  packages/integrations/src/index.ts
  packages/integrations/src/interfaces/health-monitoring/healt-monitoring.ts
  packages/integrations/src/openmediavault/openmediavault-integration.ts
  packages/integrations/src/openmediavault/openmediavault-types.ts
  packages/integrations/src/types.ts
  packages/old-import/src/widgets/definitions/index.ts
  packages/old-import/src/widgets/options.ts
  packages/translation/src/lang/en.ts
  packages/widgets/src/health-monitoring/component.tsx
  packages/widgets/src/health-monitoring/index.ts
  packages/widgets/src/health-monitoring/serverData.ts
  packages/widgets/src/index.tsx
Labels: enhancement, widget:system-health

#1208 fix: sensitive data can be leaked through query parameters
  apps/tasks/src/undici-log-agent-override.ts
Labels: bug
