Repository homarr-labs/homarr, pull requests merged in 2024-07, with the labels that each got.

#663 feat: add calendar widget
  .gitignore
  .vscode/settings.json
  apps/nextjs/public/images/apps/imdb.png
  apps/nextjs/public/images/apps/lidarr.svg
  apps/nextjs/public/images/apps/radarr.svg
  apps/nextjs/public/images/apps/readarr.svg
  apps/nextjs/public/images/apps/sonarr.svg
  apps/nextjs/public/images/apps/the-tvdb.svg
  apps/nextjs/public/images/apps/tmdb.png
  apps/nextjs/public/images/apps/truenas.svg
  apps/nextjs/public/images/apps/unraid-alt.svg
  apps/tasks/package.json
  packages/api/src/middlewares/integration.ts
  packages/api/src/router/widgets/calendar.ts
  packages/api/src/router/widgets/index.ts
  packages/cron-jobs/src/index.ts
  packages/cron-jobs/src/jobs/integrations/media-organizer.ts
  packages/definitions/src/widget.ts
  packages/integrations/src/base/creator.ts
  packages/integrations/src/calendar-types.ts
  packages/integrations/src/index.ts
  packages/integrations/src/media-organizer/sonarr/sonarr-integration.ts
  packages/integrations/src/types.ts
  packages/redis/src/index.ts
  packages/redis/src/lib/channel.ts
  packages/translation/src/lang/en.ts
  packages/widgets/src/calendar/calendar-event-list.module.css
  packages/widgets/src/calendar/calendar-event-list.tsx
  packages/widgets/src/calendar/calender-day.tsx
  packages/widgets/src/calendar/component.module.css
  packages/widgets/src/calendar/component.tsx
  packages/widgets/src/calendar/index.ts
  packages/widgets/src/calendar/serverData.ts
  packages/widgets/src/definition.ts
  packages/widgets/src/index.tsx
  packages/widgets/src/server/runner.tsx
  pnpm-lock.yaml
Labels: enhancement

#672 feat: add jellyfin integration
  .vscode/settings.json
  apps/nextjs/src/components/board/sections/content.tsx
  packages/api/src/router/widgets/calendar.ts
  packages/api/src/router/widgets/index.ts
  packages/api/src/router/widgets/media-server.ts
  packages/cron-jobs/src/index.ts
  packages/cron-jobs/src/jobs/integrations/media-organizer.ts
  packages/cron-jobs/src/jobs/integrations/media-server.ts
  packages/definitions/src/widget.ts
  packages/integrations/package.json
  packages/integrations/src/base/creator.ts
  packages/integrations/src/index.ts
  packages/integrations/src/interfaces/media-server/session.ts
  packages/integrations/src/jellyfin/jellyfin-integration.ts
  packages/redis/package.json
  packages/redis/src/index.ts
  packages/redis/src/lib/channel.ts
  packages/translation/src/lang/en.ts
  packages/widgets/package.json
  packages/widgets/src/calendar/serverData.ts
  packages/widgets/src/index.tsx
  packages/widgets/src/media-server/component.tsx
  packages/widgets/src/media-server/index.ts
  packages/widgets/src/media-server/serverData.ts
  pnpm-lock.yaml
Labels: enhancement

#743 fix: controller is already closed trpc subscription observable error
  packages/api/src/router/cron-jobs.ts
  packages/api/src/router/log.ts
  packages/api/src/router/user.ts
  packages/api/src/router/widgets/app.ts
  packages/api/src/router/widgets/media-server.ts
  packages/api/src/router/widgets/smart-home.ts
Labels: bug

#750 fix: memory leak caused by many unclosed redis subscriptions
  packages/api/src/router/cron-jobs.ts
  packages/api/src/router/log.ts
  packages/api/src/router/widgets/app.ts
  packages/api/src/router/widgets/media-server.ts
  packages/api/src/router/widgets/smart-home.ts
  packages/redis/src/lib/channel-subscription-tracker.ts
  packages/redis/src/lib/channel.ts
Labels: bug

#752 feat: add docker actions
  apps/nextjs/src/app/[locale]/manage/tools/docker/docker-table.tsx
  apps/nextjs/src/app/[locale]/manage/tools/docker/page.tsx
  packages/api/src/router/docker/docker-router.ts
  packages/translation/src/lang/en.ts
Labels: enhancement

#754 fix: manage links wrong
  apps/nextjs/src/app/[locale]/manage/page.tsx
Labels: bug

#725 feat: add integration access settings
  apps/nextjs/src/app/[locale]/boards/[name]/settings/_access.tsx
  apps/nextjs/src/app/[locale]/boards/[name]/settings/_access/board-access-table-rows.tsx
  apps/nextjs/src/app/[locale]/boards/[name]/settings/_access/form.ts
  apps/nextjs/src/app/[locale]/boards/[name]/settings/_access/inherit-access.tsx
  apps/nextjs/src/app/[locale]/boards/[name]/settings/_access/user-access.tsx
  apps/nextjs/src/app/[locale]/boards/[name]/settings/_board-access.tsx
  apps/nextjs/src/app/[locale]/boards/[name]/settings/page.tsx
  apps/nextjs/src/app/[locale]/manage/integrations/_components/integration-access-settings.tsx
  apps/nextjs/src/app/[locale]/manage/integrations/edit/[id]/page.tsx
  apps/nextjs/src/app/[locale]/manage/integrations/new/page.tsx
  apps/nextjs/src/app/[locale]/manage/users/groups/[id]/_transfer-group-ownership.tsx
  apps/nextjs/src/app/[locale]/manage/users/groups/[id]/members/_add-group-member.tsx
  apps/nextjs/src/components/access/access-settings.tsx
  apps/nextjs/src/components/access/access-table-rows.tsx
  apps/nextjs/src/components/access/context.tsx
  apps/nextjs/src/components/access/form.ts
  apps/nextjs/src/components/access/group-access-form.tsx
  apps/nextjs/src/components/access/group-select-modal.tsx
  apps/nextjs/src/components/access/inherit-access-table.tsx
  apps/nextjs/src/components/access/user-access-form.tsx
  apps/nextjs/src/components/access/user-select-modal.tsx
  packages/api/src/router/board.ts
  packages/api/src/router/board/board-access.ts
  packages/api/src/router/integration/integration-access.ts
  packages/api/src/router/integration/integration-router.ts
  packages/api/src/router/test/board.spec.ts
  packages/api/src/router/test/board/board-access.spec.ts
  packages/api/src/router/test/group.spec.ts
  packages/api/src/router/test/integration/integration-access.spec.ts
  packages/api/src/router/test/integration/integration-router.spec.ts
  packages/auth/permissions/board-permissions.ts
  packages/auth/permissions/index.ts
  packages/auth/permissions/integration-permissions.ts
  packages/auth/permissions/test/board-permissions.spec.ts
  packages/auth/permissions/test/integration-permissions.spec.ts
  packages/db/migrations/mysql/0004_noisy_giant_girl.sql
  packages/db/migrations/mysql/meta/0004_snapshot.json
  packages/db/migrations/mysql/meta/_journal.json
  packages/db/migrations/sqlite/0004_peaceful_red_ghost.sql
  packages/db/migrations/sqlite/meta/0002_snapshot.json
  packages/db/migrations/sqlite/meta/0004_snapshot.json
  packages/db/migrations/sqlite/meta/_journal.json
  packages/db/schema/mysql.ts
  packages/db/schema/sqlite.ts
  packages/definitions/src/permissions.ts
  packages/definitions/src/test/permissions.spec.ts
  packages/translation/src/lang/en.ts
  packages/validation/src/board.ts
  packages/validation/src/integration.ts
  packages/validation/src/permissions.ts
Labels: enhancement

#756 feat: add integration access check to middlewares
  packages/api/src/middlewares/integration.ts
  packages/api/src/router/widgets/calendar.ts
  packages/api/src/router/widgets/dns-hole.ts
  packages/api/src/router/widgets/media-server.ts
  packages/api/src/router/widgets/smart-home.ts
  packages/auth/callbacks.ts
  packages/auth/package.json
  packages/auth/permissions/integration-query-permissions.ts
  packages/auth/permissions/test/integration-query-permissions.spec.ts
  packages/auth/server.ts
  packages/auth/test/callbacks.spec.ts
Labels: enhancement

#777 fix: docker build
  apps/websocket/package.json
Labels: bug

#500 feat: add ldap and oidc sso
  Dockerfile
  apps/nextjs/src/app/[locale]/auth/login/_login-form.tsx
  apps/nextjs/src/app/[locale]/auth/login/page.tsx
  apps/nextjs/src/app/api/auth/[...nextauth]/route.ts
  packages/auth/adapter.ts
  packages/auth/configuration.ts
  packages/auth/env.mjs
  packages/auth/index.ts
  packages/auth/next.ts
  packages/auth/package.json
  packages/auth/providers/credentials.ts
  packages/auth/providers/credentials/authorization/basic-authorization.ts
  packages/auth/providers/credentials/authorization/ldap-authorization.ts
  packages/auth/providers/credentials/credentials-provider.ts
  packages/auth/providers/credentials/ldap-client.ts
  packages/auth/providers/empty/empty-provider.ts
  packages/auth/providers/filter-providers.ts
  packages/auth/providers/oidc/oidc-provider.ts
  packages/auth/providers/test/basic-authorization.spec.ts
  packages/auth/providers/test/credentials.spec.ts
  packages/auth/providers/test/ldap-authorization.spec.ts
  packages/auth/redirect.ts
  packages/auth/test/redirect.spec.ts
  packages/translation/src/lang/en.ts
  packages/validation/src/user.ts
  pnpm-lock.yaml
  turbo.json
Labels: enhancement

#856 feat: allow no secrets for integration
  apps/nextjs/src/app/[locale]/manage/integrations/new/_integration-new-form.tsx
  packages/translation/src/lang/en.ts
Labels: enhancement

#846 fix: job translations
  apps/nextjs/src/app/[locale]/manage/tools/tasks/_components/jobs-list.tsx
Labels: bug

#860 fix: deployment pipeline for docker not working
  .github/workflows/deployment-docker-image.yml
  Dockerfile
  apps/nextjs/next.config.mjs
  development/docker-run.cmd
  packages/log/src/index.mjs
  packages/redis/src/lib/connection.ts
  turbo.json
Labels: bug

#871 feat: restrict non credential provider interactions
  apps/nextjs/src/app/[locale]/auth/invite/[id]/page.tsx
  apps/nextjs/src/app/[locale]/manage/layout.tsx
  apps/nextjs/src/app/[locale]/manage/page.tsx
  apps/nextjs/src/app/[locale]/manage/users/[userId]/general/_components/_profile-avatar-form.tsx
  apps/nextjs/src/app/[locale]/manage/users/[userId]/general/_components/_profile-form.tsx
  apps/nextjs/src/app/[locale]/manage/users/[userId]/general/page.tsx
  apps/nextjs/src/app/[locale]/manage/users/[userId]/layout.tsx
  apps/nextjs/src/app/[locale]/manage/users/[userId]/security/page.tsx
  apps/nextjs/src/app/[locale]/manage/users/groups/[id]/members/page.tsx
  apps/nextjs/src/app/[locale]/manage/users/invites/page.tsx
  apps/nextjs/src/components/layout/navigation.tsx
  packages/api/src/router/group.ts
  packages/api/src/router/invite.ts
  packages/api/src/router/invite/checks.ts
  packages/api/src/router/test/group.spec.ts
  packages/api/src/router/test/invite.spec.ts
  packages/api/src/router/test/user.spec.ts
  packages/api/src/router/user.ts
  packages/auth/providers/check-provider.ts
  packages/auth/providers/credentials/authorization/basic-authorization.ts
  packages/auth/providers/credentials/authorization/ldap-authorization.ts
  packages/auth/providers/credentials/credentials-provider.ts
  packages/auth/providers/oidc/oidc-provider.ts
  packages/auth/providers/test/ldap-authorization.spec.ts
  packages/auth/server.ts
  packages/db/migrations/mysql/0005_soft_microbe.sql
  packages/db/migrations/mysql/meta/0005_snapshot.json
  packages/db/migrations/mysql/meta/_journal.json
  packages/db/migrations/sqlite/0005_lean_random.sql
  packages/db/migrations/sqlite/meta/0005_snapshot.json
  packages/db/migrations/sqlite/meta/_journal.json
  packages/db/schema/mysql.ts
  packages/db/schema/sqlite.ts
  packages/definitions/src/auth.ts
  packages/definitions/src/index.ts
  packages/translation/src/lang/en.ts
Labels: enhancement

#873 fix: mantine-react-table not localized #333
  apps/nextjs/src/app/[locale]/manage/tools/docker/docker-table.tsx
  apps/nextjs/src/app/[locale]/manage/users/_components/user-list.tsx
  apps/nextjs/src/app/[locale]/manage/users/invites/_components/invite-list.tsx
  packages/translation/package.json
  packages/translation/src/lang/de.ts
  packages/translation/src/lang/en.ts
  packages/ui/package.json
  packages/ui/src/hooks/index.ts
  packages/ui/src/hooks/use-translated-mantine-react-table.ts
  packages/widgets/src/media-server/component.tsx
  pnpm-lock.yaml
Labels: bug

#760 feat: add rss widget
  apps/nextjs/src/app/[locale]/layout.tsx
  apps/nextjs/src/styles/scroll-area.scss
  packages/api/src/middlewares/item.ts
  packages/api/src/router/widgets/index.ts
  packages/api/src/router/widgets/rssFeed.ts
  packages/cron-jobs-core/src/creator.ts
  packages/cron-jobs/package.json
  packages/cron-jobs/src/index.ts
  packages/cron-jobs/src/jobs/rss-feeds.ts
  packages/definitions/src/widget.ts
  packages/redis/src/index.ts
  packages/redis/src/lib/channel.ts
  packages/translation/src/lang/en.ts
  packages/widgets/package.json
  packages/widgets/src/_inputs/index.ts
  packages/widgets/src/_inputs/widget-multi-text-input.tsx
  packages/widgets/src/index.tsx
  packages/widgets/src/options.ts
  packages/widgets/src/rssFeed/component.module.scss
  packages/widgets/src/rssFeed/component.tsx
  packages/widgets/src/rssFeed/index.ts
  packages/widgets/src/rssFeed/serverData.ts
  pnpm-lock.yaml
Labels: enhancement, widget:rss-feed

#872 fix: missing breadcrumb translation, wrong spacing in user layout
  apps/nextjs/src/app/[locale]/manage/users/[userId]/layout.tsx
  packages/translation/src/lang/en.ts
Labels: bug

#875 fix: videos not playing automatically on iOS / mobile
  apps/nextjs/src/components/layout/background.tsx
Labels: bug

#879 feat: add validation to widget edit modal inputs
  packages/validation/src/form/i18n.ts
  packages/validation/src/location.ts
  packages/widgets/src/_inputs/widget-location-input.tsx
  packages/widgets/src/modals/widget-edit-modal.tsx
  packages/widgets/src/options.ts
Labels: enhancement

#880 fix: overview in series of sonarr schema is optional
  packages/integrations/src/media-organizer/sonarr/sonarr-integration.ts
Labels: bug

#881 fix: fetch timeout for external requests to small
  packages/api/src/router/location.ts
  packages/api/src/router/widgets/weather.ts
  packages/common/src/fetch-with-timeout.ts
  packages/common/src/index.ts
  packages/icons/package.json
  packages/icons/src/repositories/github.icon-repository.ts
  packages/icons/src/repositories/jsdelivr.icon-repository.ts
  packages/ping/src/index.ts
  pnpm-lock.yaml
Labels: bug
