Repository homarr-labs/homarr, pull requests merged in 2025-09, with the labels that each got.

#3979 feat(kubernetes): add Talos providers
  packages/api/src/router/kubernetes/router/cluster.ts
Labels: enhancement

#3736 fix: add dns caching
  apps/tasks/src/main.ts
  apps/tasks/src/overrides.ts
  package.json
  packages/common/package.json
  packages/common/src/dns.ts
  packages/common/src/fetch-agent.ts
  pnpm-lock.yaml
Labels: bug

#3998 fix(deps): tsx breaks imports like dns-caching
  .github/renovate.json5
  apps/tasks/package.json
  apps/websocket/package.json
  packages/db/package.json
  packages/definitions/package.json
  pnpm-lock.yaml
Labels: bug

#4000 feat(rss-widget): add hide description option
  packages/old-import/src/widgets/options.ts
  packages/translation/src/lang/en.json
  packages/widgets/src/rssFeed/component.tsx
  packages/widgets/src/rssFeed/index.ts
Labels: enhancement

#3999 fix(header): avatar menu flashes when opening on mobile
  apps/nextjs/src/components/layout/header.tsx
Labels: bug

#4007 fix(dns): disable caching by default
  packages/common/env.ts
  packages/common/src/dns.ts
Labels: bug

#4015 fix(video-widget): hls videos not working
  apps/nextjs/next.config.ts
  packages/widgets/src/video/component.tsx
Labels: bug

#4017 fix(iframe): disable scrolling not working
  packages/old-import/src/widgets/options.ts
  packages/widgets/src/iframe/component.tsx
  packages/widgets/src/iframe/index.ts
Labels: bug

#4018 fix(adguard-integration): parse error with protection_disabled_duration field
  packages/integrations/src/adguard-home/adguard-home-types.ts
Labels: bug

#4032 fix(plex-integration): unknown badge shown for added tv-shows
  packages/integrations/src/plex/plex-integration.ts
Labels: bug

#3968 feat(integration): add github app authentication
  apps/nextjs/src/app/[locale]/manage/integrations/_components/secrets/integration-secret-icons.ts
  apps/nextjs/src/app/[locale]/manage/integrations/_components/secrets/integration-secret-inputs.tsx
  packages/api/src/router/integration/integration-test-connection.ts
  packages/api/src/router/test/integration/integration-test-connection.spec.ts
  packages/common/package.json
  packages/common/src/errors/http/handlers/index.ts
  packages/common/src/errors/http/handlers/octokit-http-error-handler.ts
  packages/definitions/src/integration.ts
  packages/integrations/package.json
  packages/integrations/src/base/errors/http/index.ts
  packages/integrations/src/github-container-registry/github-container-registry-integration.ts
  packages/integrations/src/github/github-integration.ts
  packages/translation/src/lang/en.json
  pnpm-lock.yaml
Labels: enhancement

#4064 feat(notebook-widget): add confirmation on dismiss
  packages/translation/src/lang/en.json
  packages/widgets/src/notebook/notebook.tsx
Labels: enhancement

#4074 feat(tasks): add one second interval
  apps/nextjs/src/app/[locale]/manage/tools/tasks/_components/tasks-table.tsx
Labels: enhancement

#4073 ci(on-release): update bug report template failing
  .github/workflows/on-release.yml
Labels: bug

#4077 docs(readme): add screenshot of example dashboard
  docs/README.md
  docs/img/screenshot.png
Labels: documentation

#3980 feat(integrations): add ICal
  apps/nextjs/src/app/[locale]/manage/integrations/_components/secrets/integration-secret-icons.ts
  apps/nextjs/src/app/[locale]/manage/integrations/edit/[id]/_integration-edit-form.tsx
  apps/nextjs/src/app/[locale]/manage/integrations/new/_integration-new-form.tsx
  packages/common/src/fetch-agent.ts
  packages/common/src/test/fetch-agent.spec.ts
  packages/definitions/src/integration.ts
  packages/integrations/package.json
  packages/integrations/src/base/creator.ts
  packages/integrations/src/ical/ical-integration.ts
  packages/integrations/src/index.ts
  packages/integrations/src/interfaces/calendar/calendar-types.ts
  packages/integrations/src/media-organizer/lidarr/lidarr-integration.ts
  packages/integrations/src/media-organizer/radarr/radarr-integration.ts
  packages/integrations/src/media-organizer/readarr/readarr-integration.ts
  packages/integrations/src/media-organizer/sonarr/sonarr-integration.ts
  packages/integrations/src/mock/data/calendar.ts
  packages/integrations/src/nextcloud/nextcloud.integration.ts
  packages/translation/src/lang/en.json
  packages/widgets/src/calendar/calendar-event-list.tsx
  packages/widgets/src/calendar/calender-day.tsx
  packages/widgets/src/calendar/component.tsx
  pnpm-lock.yaml
Labels: enhancement

#4086 feat(system-resources-widget): add label display mode option
  packages/translation/src/lang/en.json
  packages/widgets/src/system-resources/chart/combined-network-traffic.tsx
  packages/widgets/src/system-resources/chart/common-chart.tsx
  packages/widgets/src/system-resources/chart/cpu-chart.tsx
  packages/widgets/src/system-resources/chart/memory-chart.tsx
  packages/widgets/src/system-resources/chart/network-traffic.tsx
  packages/widgets/src/system-resources/component.tsx
  packages/widgets/src/system-resources/index.ts
Labels: enhancement

#4093 feat(system-resources-widget): add has-shadow option
  package.json
  packages/translation/src/lang/en.json
  packages/widgets/src/system-resources/chart/combined-network-traffic.tsx
  packages/widgets/src/system-resources/chart/common-chart.tsx
  packages/widgets/src/system-resources/chart/cpu-chart.tsx
  packages/widgets/src/system-resources/chart/memory-chart.tsx
  packages/widgets/src/system-resources/chart/network-traffic.tsx
  packages/widgets/src/system-resources/component.tsx
  packages/widgets/src/system-resources/index.ts
  pnpm-lock.yaml
Labels: enhancement

#4154 feat(calendar): add periodic live updates
  packages/api/src/router/widgets/calendar.ts
  packages/widgets/src/calendar/component.tsx
Labels: enhancement
