Repository homarr-labs/homarr, pull requests merged in 2025-04, with the labels that each got.

#2760 fix(nextcloud): issue with self signed certificates
  packages/certificates/src/server.ts
  packages/integrations/src/nextcloud/nextcloud.integration.ts
Labels: bug

#2782 fix: update check blocks page loading
  apps/nextjs/src/components/layout/header/update.tsx
  apps/nextjs/src/components/layout/header/user.tsx
  apps/nextjs/src/components/user-avatar-menu.tsx
  packages/request-handler/src/update-checker.ts
Labels: bug

#2770 feat(boards): add upload buttons for background, favicon and logo
  apps/nextjs/src/app/[locale]/boards/[name]/settings/_background.tsx
  apps/nextjs/src/app/[locale]/boards/[name]/settings/_general.tsx
  packages/forms-collection/src/icon-picker/icon-picker.tsx
  packages/translation/src/lang/en.json
Labels: enhancement

#2236 feat: unifi controller integration
  apps/nextjs/src/app/[locale]/boards/(content)/_theme.tsx
  packages/api/src/router/widgets/index.ts
  packages/api/src/router/widgets/network-controller.ts
  packages/cron-job-runner/src/index.ts
  packages/cron-jobs/src/index.ts
  packages/cron-jobs/src/jobs/integrations/network-controller.ts
  packages/definitions/src/integration.ts
  packages/definitions/src/widget.ts
  packages/integrations/src/base/creator.ts
  packages/integrations/src/base/integration.ts
  packages/integrations/src/interfaces/network-controller-summary/network-controller-summary-integration.ts
  packages/integrations/src/interfaces/network-controller-summary/network-controller-summary-types.ts
  packages/integrations/src/types.ts
  packages/integrations/src/unifi-controller/unifi-controller-integration.ts
  packages/integrations/src/unifi-controller/unifi-controller-types.ts
  packages/request-handler/src/network-controller.ts
  packages/translation/src/lang/en.json
  packages/widgets/src/index.tsx
  packages/widgets/src/network-controller/network-status/component.tsx
  packages/widgets/src/network-controller/network-status/index.ts
  packages/widgets/src/network-controller/network-status/variants/stat-row.tsx
  packages/widgets/src/network-controller/network-status/variants/wifi-variant.tsx
  packages/widgets/src/network-controller/network-status/variants/wired-variant.tsx
  packages/widgets/src/network-controller/summary/component.tsx
  packages/widgets/src/network-controller/summary/index.ts
Labels: enhancement, integration

#2813 fix(medias): upload size limited by nginx to 1mb
  nginx.conf
  packages/validation/src/media.ts
Labels: bug

#2832 fix(security): missing authorization check for changes to notebook widget
  packages/api/src/router/widgets/notebook.ts
  packages/widgets/src/notebook/notebook.tsx
Labels: bug

#2226 feat: Support aria2 in download widget
  packages/definitions/src/integration.ts
  packages/integrations/package.json
  packages/integrations/src/base/creator.ts
  packages/integrations/src/download-client/aria2/aria2-integration.ts
  packages/integrations/src/download-client/aria2/aria2-types.ts
  packages/integrations/src/download-client/deluge/deluge-integration.ts
  packages/integrations/src/download-client/nzbget/nzbget-integration.ts
  packages/integrations/src/download-client/qbittorrent/qbittorrent-integration.ts
  packages/integrations/src/download-client/sabnzbd/sabnzbd-integration.ts
  packages/integrations/src/download-client/transmission/transmission-integration.ts
  packages/integrations/src/index.ts
  packages/integrations/src/interfaces/downloads/download-client-items.ts
  packages/integrations/src/interfaces/downloads/download-client-status.ts
  packages/integrations/test/aria2.spec.ts
  packages/old-import/src/widgets/options.ts
  packages/translation/src/lang/en.json
  packages/widgets/src/downloads/component.tsx
  packages/widgets/src/downloads/index.ts
  pnpm-lock.yaml
Labels: enhancement, integration

#2681 feat: [proposal] quick add app to board
  apps/nextjs/src/app/[locale]/boards/(content)/_header-actions.tsx
  apps/nextjs/src/components/board/items/actions/create-item.ts
  packages/modals-collection/src/apps/app-select-modal.tsx
  packages/modals-collection/src/apps/index.ts
  packages/modals-collection/src/apps/quick-add-app/quick-add-app-modal.tsx
  packages/translation/src/lang/en.json
Labels: ux

#2885 fix: calculate available space correctly and filter unmounted drives
  packages/integrations/src/dashdot/dashdot-integration.ts
Labels: bug

#2910 fix(certificates): improve validation and prevent crash
  apps/nextjs/src/app/[locale]/manage/tools/certificates/page.tsx
  packages/api/src/router/certificates/certificate-router.ts
  packages/certificates/src/server.ts
  packages/translation/src/lang/en.json
  packages/validation/src/certificates.ts
Labels: bug

#2909 feat(widgets): add title to advanced options
  apps/nextjs/src/app/[locale]/widgets/[kind]/_content.tsx
  apps/nextjs/src/components/board/items/actions/create-item.ts
  apps/nextjs/src/components/board/items/actions/test/duplicate-item.spec.ts
  apps/nextjs/src/components/board/items/actions/test/mocks/item-mock.ts
  apps/nextjs/src/components/board/items/item-content.module.css
  apps/nextjs/src/components/board/items/item-content.tsx
  packages/translation/src/lang/en.json
  packages/validation/src/shared.ts
  packages/widgets/src/modals/widget-advanced-options-modal.tsx
Labels: enhancement

#2497 feat: add releases widget
  packages/api/src/router/widgets/index.ts
  packages/api/src/router/widgets/releases.ts
  packages/definitions/src/widget.ts
  packages/request-handler/src/releases-providers.ts
  packages/request-handler/src/releases.ts
  packages/translation/src/lang/en.json
  packages/ui/src/components/masked-image.tsx
  packages/ui/src/components/masked-or-normal-image.tsx
  packages/widgets/package.json
  packages/widgets/src/_inputs/index.ts
  packages/widgets/src/_inputs/widget-multiReleasesRepositories-input.tsx
  packages/widgets/src/index.tsx
  packages/widgets/src/options.ts
  packages/widgets/src/releases/component.module.scss
  packages/widgets/src/releases/component.tsx
  packages/widgets/src/releases/index.ts
  packages/widgets/src/releases/releases-providers.ts
  packages/widgets/src/releases/releases-repository.ts
  pnpm-lock.yaml
Labels: enhancement

#2894 feat: migrate to unifi package
  .vscode/settings.json
  apps/tasks/package.json
  apps/websocket/package.json
  packages/integrations/package.json
  packages/integrations/src/unifi-controller/unifi-controller-integration.ts
  packages/integrations/src/unifi-controller/unifi-controller-types.ts
  pnpm-lock.yaml
Labels: bug

#2972 fix: cannot find module http-cookie-agent/http
  .dockerignore
  apps/tasks/package.json
  apps/websocket/package.json
  pnpm-lock.yaml
Labels: bug

#2962 fix(releases-widget): improve ui for smaller widgets
  packages/widgets/src/releases/component.tsx
Labels: bug
