Repository homarr-labs/homarr, pull requests merged in 2025-08, with the labels that each got.

#3737 feat(api): add info endpoint
  packages/api/src/root.ts
  packages/api/src/router/info.ts
Labels: enhancement

#3739 fix(groups): saving permissions with none activated causes error
  packages/api/src/router/group.ts
Labels: bug

#3538 feat: system resources widget
  apps/nextjs/src/components/board/items/item-content.tsx
  packages/cron-jobs/src/jobs/integrations/health-monitoring.ts
  packages/definitions/src/widget.ts
  packages/integrations/src/dashdot/dashdot-integration.ts
  packages/integrations/src/interfaces/health-monitoring/health-monitoring-types.ts
  packages/integrations/src/mock/data/system-health-monitoring.ts
  packages/integrations/src/openmediavault/openmediavault-integration.ts
  packages/integrations/src/opnsense/opnsense-integration.ts
  packages/redis/src/index.ts
  packages/redis/src/lib/channel.ts
  packages/redis/src/lib/channels/history-channel.ts
  packages/translation/src/lang/en.json
  packages/ui/src/styles.css
  packages/widgets/src/health-monitoring/rings/memory-ring.tsx
  packages/widgets/src/health-monitoring/system-health.tsx
  packages/widgets/src/index.tsx
  packages/widgets/src/system-resources/chart/combined-network-traffic.tsx
  packages/widgets/src/system-resources/chart/common-chart.tsx
  packages/widgets/src/system-resources/chart/cpu-chart.tsx
  packages/widgets/src/system-resources/chart/memory-chart.tsx
  packages/widgets/src/system-resources/chart/network-traffic.tsx
  packages/widgets/src/system-resources/component.module.css
  packages/widgets/src/system-resources/component.tsx
  packages/widgets/src/system-resources/index.ts
Labels: enhancement

#3873 feat(app-widget): multiline description
  apps/nextjs/src/app/[locale]/manage/apps/page.tsx
  packages/forms-collection/src/new-app/_form.tsx
  packages/widgets/src/app/component.tsx
Labels: enhancement

#3881 ci: add on-release workflow to trigger docs-release, update bug-report-template and update security-policy
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/on-release.yml
  SECURITY.md
  package.json
  scripts/update-bug-report-template.mts
Labels: dx

#3919 fix(security): deepsource issues
  package.json
  pnpm-lock.yaml
Labels: bug
