Repository homarr-labs/homarr, pull requests merged in 2025-03, with the labels that each got.

#2453 chore(license): update license property in package-json to match repo…
  apps/tasks/package.json
  apps/websocket/package.json
  packages/analytics/package.json
  packages/api/package.json
  packages/auth/package.json
  packages/boards/package.json
  packages/certificates/package.json
  packages/cli/package.json
  packages/common/package.json
  packages/cron-job-runner/package.json
  packages/cron-job-status/package.json
  packages/cron-jobs-core/package.json
  packages/cron-jobs/package.json
  packages/db/package.json
  packages/definitions/package.json
  packages/docker/package.json
  packages/env/package.json
  packages/form/package.json
  packages/forms-collection/package.json
  packages/icons/package.json
  packages/integrations/package.json
  packages/log/package.json
  packages/modals-collection/package.json
  packages/modals/package.json
  packages/notifications/package.json
  packages/old-import/package.json
  packages/old-schema/package.json
  packages/ping/package.json
  packages/redis/package.json
  packages/request-handler/package.json
  packages/server-settings/package.json
  packages/settings/package.json
  packages/spotlight/package.json
  packages/translation/package.json
  packages/ui/package.json
  packages/validation/package.json
  packages/widgets/package.json
  tooling/eslint/package.json
Labels: documentation

#2454 fix(boards): case-sensitive board names in url
  packages/api/src/router/board.ts
Labels: bug

#2456 fix(old-import): default logo and favicon not replaced
  packages/old-import/src/mappers/map-board.ts
Labels: bug

#2412 feat: use fetch with trusted certificates for oidc
  packages/auth/package.json
  packages/auth/providers/oidc/oidc-provider.ts
  packages/auth/test/events.spec.ts
  pnpm-lock.yaml
Labels: enhancement

#2464 fix(media-request): inconsistent sorting and reordering
  packages/api/src/router/widgets/media-requests.ts
  packages/widgets/src/media-requests/list/component.tsx
Labels: bug

#2465 feat(media-request): show request status
  packages/translation/src/lang/en.json
  packages/widgets/src/media-requests/list/component.tsx
Labels: enhancement

#2468 fix(logs): add special case for axios error to prevent huge error messages
  packages/cron-jobs-core/src/creator.ts
Labels: bug

#2466 feat(integration): add emby integration
  packages/definitions/src/integration.ts
  packages/integrations/src/base/creator.ts
  packages/integrations/src/emby/emby-integration.ts
  packages/integrations/src/jellyfin/jellyfin-integration.ts
  packages/widgets/src/media-server/index.ts
Labels: enhancement, integration

#2472 feat: add sigterm support
  development/docker-run.cmd
  scripts/entrypoint.sh
  scripts/run.sh
Labels: enhancement

#2448 feat(pihole): add support for v6
  packages/api/src/router/integration/integration-router.ts
  packages/api/src/router/integration/integration-test-connection.ts
  packages/api/src/router/search-engine/search-engine-router.ts
  packages/api/src/router/test/integration/integration-test-connection.spec.ts
  packages/api/src/router/widgets/dns-hole.ts
  packages/api/src/router/widgets/downloads.ts
  packages/api/src/router/widgets/indexer-manager.ts
  packages/api/src/router/widgets/media-requests.ts
  packages/api/src/router/widgets/smart-home.ts
  packages/integrations/src/base/creator.ts
  packages/integrations/src/base/error.ts
  packages/integrations/src/base/session-store.ts
  packages/integrations/src/index.ts
  packages/integrations/src/interfaces/dns-hole-summary/dns-hole-summary-integration.ts
  packages/integrations/src/pi-hole/pi-hole-integration-factory.ts
  packages/integrations/src/pi-hole/v5/pi-hole-integration-v5.ts
  packages/integrations/src/pi-hole/v5/pi-hole-schemas-v5.ts
  packages/integrations/src/pi-hole/v6/pi-hole-integration-v6.ts
  packages/integrations/src/pi-hole/v6/pi-hole-schemas-v6.ts
  packages/integrations/src/types.ts
  packages/integrations/test/pi-hole.spec.ts
  packages/redis/src/index.ts
  packages/redis/src/lib/channel.ts
  packages/request-handler/src/calendar.ts
  packages/request-handler/src/dns-hole.ts
  packages/request-handler/src/downloads.ts
  packages/request-handler/src/health-monitoring.ts
  packages/request-handler/src/indexer-manager.ts
  packages/request-handler/src/media-request-list.ts
  packages/request-handler/src/media-request-stats.ts
  packages/request-handler/src/media-server.ts
  packages/request-handler/src/media-transcoding.ts
  packages/request-handler/src/smart-home-entity-state.ts
Labels: enhancement

#2441 fix: docker add to homarr layout overflow
  apps/nextjs/src/app/[locale]/manage/tools/docker/docker-table.tsx
  packages/modals-collection/src/docker/add-docker-app-to-homarr.tsx
Labels: bug

#2467 fix(integration): store omv session in redis
  packages/integrations/src/base/session-store.ts
  packages/integrations/src/openmediavault/openmediavault-integration.ts
  packages/integrations/src/pi-hole/v6/pi-hole-integration-v6.ts
  packages/integrations/test/pi-hole.spec.ts
Labels: bug

#2491 fix: affix hides pagination on mobile
  apps/nextjs/src/app/[locale]/manage/apps/page.tsx
  apps/nextjs/src/app/[locale]/manage/medias/page.tsx
  apps/nextjs/src/app/[locale]/manage/search-engines/page.tsx
Labels: bug

#2527 fix(pi-hole): wrong fetch used in factory
  packages/integrations/src/pi-hole/pi-hole-integration-factory.ts
Labels: bug

#2522 fix(import): autofix missing sizes of items with grid-algorithm
  packages/old-import/src/import/collections/board-collection.ts
  packages/old-import/src/mappers/map-column-count.ts
  packages/old-import/src/move-widgets-and-apps-merge.ts
  packages/old-import/src/prepare/prepare-items.ts
  packages/old-schema/src/index.ts
  packages/old-schema/src/tile.ts
Labels: bug

#2512 feat(widgets): add border color option to advanced-options
  apps/nextjs/src/app/[locale]/widgets/[kind]/_content.tsx
  apps/nextjs/src/components/board/items/actions/create-item.ts
  apps/nextjs/src/components/board/items/actions/test/duplicate-item.spec.ts
  apps/nextjs/src/components/board/items/actions/test/mocks/item-mock.ts
  apps/nextjs/src/components/board/items/item-content.tsx
  packages/translation/src/lang/en.json
  packages/validation/src/shared.ts
  packages/widgets/src/modals/widget-advanced-options-modal.tsx
  packages/widgets/src/modals/widget-edit-modal.tsx
Labels: enhancement

#2536 fix(bookmarks): improve responsive styles
  packages/old-import/src/widgets/options.ts
  packages/translation/src/lang/en.json
  packages/widgets/src/bookmarks/component.tsx
  packages/widgets/src/bookmarks/index.tsx
Labels: bug

#2535 fix(dns-summary): improve responsive styles
  packages/widgets/src/dns-hole/summary/component.tsx
Labels: bug

#2534 fix(dns-controls): improve responsive styles
  packages/widgets/src/dns-hole/controls/component.tsx
  packages/widgets/src/widgets-common.css
Labels: bug

#2537 fix(app): improve responsive styles
  packages/widgets/src/app/component.tsx
  packages/widgets/src/app/ping/ping-dot.tsx
Labels: bug

#2538 fix(calendar): improve responsive styles
  packages/widgets/src/calendar/calendar-event-list.tsx
  packages/widgets/src/calendar/calender-day.tsx
  packages/widgets/src/calendar/component.tsx
Labels: bug

#2539 fix(date-time): improve responsive styles
  packages/widgets/src/clock/component.tsx
Labels: bug

#2540 fix(smart-home): improve responsive styles
  packages/widgets/src/smart-home/entity-state/component.tsx
  packages/widgets/src/smart-home/execute-automation/component.tsx
Labels: bug

#2501 feat: add nextcloud integration
  apps/nextjs/public/images/apps/nextcloud.svg
  packages/definitions/src/integration.ts
  packages/integrations/package.json
  packages/integrations/src/base/creator.ts
  packages/integrations/src/index.ts
  packages/integrations/src/nextcloud/nextcloud.integration.ts
  packages/widgets/src/calendar/calendar-event-list.tsx
  pnpm-lock.yaml
Labels: enhancement, integration

#2541 fix(indexer-manager): improve responsive styles
  packages/widgets/src/indexer-manager/component.tsx
Labels: bug

#2543 fix(media-request-list): improve responsive styles
  packages/widgets/src/media-requests/list/component.tsx
Labels: bug

#2548 fix(media-server): improve responsive styles
  packages/translation/src/lang/en.json
  packages/widgets/src/media-server/component.tsx
Labels: bug

#2551 fix(minecraft-status): wrong api path for bedrock
  packages/request-handler/src/minecraft-server-status.ts
  packages/widgets/src/minecraft/server-status/component.tsx
Labels: bug

#2547 feat(calendar): add show-unmonitored option
  packages/api/src/router/widgets/calendar.ts
  packages/cron-jobs/src/jobs/integrations/media-organizer.ts
  packages/old-import/src/widgets/options.ts
  packages/request-handler/src/calendar.ts
  packages/translation/src/lang/en.json
  packages/widgets/src/calendar/component.tsx
  packages/widgets/src/calendar/index.ts
Labels: bug, enhancement

#2552 fix(downloads): improve responsive styles
  packages/widgets/src/downloads/component.tsx
  packages/widgets/src/widgets-common.css
Labels: bug

#2568 fix(dns-hole-summary): remove inconsistency for position of text
  packages/widgets/src/dns-hole/summary/component.tsx
Labels: bug

#2569 fix(calendar): dropdown spans over whole screen
  packages/widgets/src/calendar/calender-day.tsx
Labels: bug

#2570 fix(notebook): css for checkboxes not working
  packages/widgets/src/notebook/component.tsx
  packages/widgets/src/notebook/notebook.css
  packages/widgets/src/notebook/notebook.tsx
Labels: bug

#2566 fix(system-health): improve responsive styles
  packages/widgets/src/health-monitoring/cluster/cluster-health.tsx
  packages/widgets/src/health-monitoring/cluster/resource-accordion-item.tsx
  packages/widgets/src/health-monitoring/cluster/resource-table.tsx
  packages/widgets/src/health-monitoring/component.tsx
  packages/widgets/src/health-monitoring/rings/cpu-ring.tsx
  packages/widgets/src/health-monitoring/rings/cpu-temp-ring.tsx
  packages/widgets/src/health-monitoring/rings/memory-ring.tsx
  packages/widgets/src/health-monitoring/system-health.tsx
Labels: bug

#2574 feat(logs): improve error logs with stacked causes
  packages/log/src/index.ts
Labels: enhancement

#2463 feat(integrations): add checkbox to add app
  apps/nextjs/src/app/[locale]/manage/integrations/new/_integration-new-form.tsx
  packages/translation/src/lang/en.json
Labels: enhancement

#2593 fix: action icons not being rendered
  apps/nextjs/src/app/[locale]/manage/integrations/page.tsx
Labels: bug

#2625 fix(permissions): unable to edit board with full board permissions
  packages/auth/permissions/board-permissions.ts
Labels: bug

#2650 fix(cli): fix-usernames command only fixes lowercase usernames
  packages/cli/src/commands/fix-usernames.ts
Labels: bug

#2668 chore(deps): update trpc to v11
  apps/nextjs/package.json
  apps/nextjs/src/app/[locale]/_client-providers/trpc.tsx
  packages/api/package.json
  pnpm-lock.yaml
Labels: bug

#2704 feat: add jetbrains run profile
  .run/All Tests.run.xml
Labels: enhancement

#2703 feat(logs): improve logs by logging errors with causes and metadata
  apps/nextjs/src/app/api/[...trpc]/route.ts
  apps/nextjs/src/app/api/trpc/[trpc]/route.ts
  packages/api/src/router/integration/integration-test-connection.ts
  packages/api/src/router/update-checker.ts
  packages/auth/configuration.ts
  packages/log/src/error.ts
  packages/log/src/index.ts
  packages/log/src/metadata.ts
  packages/ping/src/index.ts
  packages/request-handler/src/lib/cached-request-integration-job-handler.ts
Labels: enhancement

#2679 feat: implement auto-select icon
  packages/forms-collection/src/new-app/_form.tsx
  packages/forms-collection/src/new-app/icon-matcher.ts
Labels: enhancement

#2711 feat(auth): add env variable to force user-info usage instead of idtoken
  packages/auth/env.ts
  packages/auth/providers/oidc/oidc-provider.ts
  turbo.json
Labels: enhancement

#2712 fix: calendar indicators
  packages/widgets/src/calendar/calender-day.tsx
  packages/widgets/src/calendar/component.tsx
Labels: enhancement

#2723 fix(import): autofix missing shapes for sidebars and some sections as well
  packages/old-import/src/import-error.ts
  packages/old-import/src/import/collections/board-collection.ts
  packages/old-import/src/import/test/board-collection.spec.ts
  packages/old-import/src/move-widgets-and-apps-merge.ts
Labels: bug

#2719 fix(auth): fusion auth returns www-authenticate token response
  packages/auth/providers/oidc/oidc-provider.ts
Labels: bug

#2725 fix(users): allow deletion of external users
  apps/nextjs/src/app/[locale]/manage/users/[userId]/general/page.tsx
Labels: bug

#2675 fix: bookmarks layout
  packages/widgets/src/bookmarks/component.tsx
Labels: bug
