Repository homarr-labs/homarr, pull requests merged in 2025-02, with the labels that each got.

#2237 ci: fix corepack issue
  Dockerfile
Labels: bug

#2212 feat: open all apps in category
  apps/nextjs/src/components/board/sections/category/category-menu-actions.tsx
  apps/nextjs/src/components/board/sections/category/category-menu.tsx
  apps/nextjs/src/components/board/sections/category/filter.ts
  packages/translation/src/lang/en.json
Labels: enhancement

#2210 feat: add api key delete
  apps/nextjs/src/app/[locale]/manage/tools/api/components/api-keys.tsx
  packages/api/src/router/apiKeys.ts
  packages/translation/src/lang/en.json
Labels: enhancement

#2247 fix: make system health temp optional
  packages/integrations/src/interfaces/health-monitoring/healt-monitoring.ts
  packages/integrations/src/openmediavault/openmediavault-integration.ts
  packages/widgets/src/health-monitoring/system-health.tsx
Labels: bug

#2211 fix: foreign key reference default search engine
  packages/api/src/router/search-engine/search-engine-router.ts
  packages/db/migrations/mysql/0023_fix_on_delete_actions.sql
  packages/db/migrations/mysql/meta/0023_snapshot.json
  packages/db/migrations/mysql/meta/_journal.json
  packages/db/migrations/sqlite/0023_fix_on_delete_actions.sql
  packages/db/migrations/sqlite/meta/0023_snapshot.json
  packages/db/migrations/sqlite/meta/_journal.json
Labels: bug

#2268 fix(calendar): info popover overlap
  packages/widgets/src/calendar/calender-day.tsx
  packages/widgets/src/calendar/component.tsx
Labels: bug

#2008 chore(integrations): change icon links to svg and new repository
  packages/api/src/router/test/integration/integration-router.spec.ts
  packages/definitions/src/integration.ts
Labels: enhancement

#2283 feat(lang): add catalan language
  packages/translation/src/config.ts
  packages/translation/src/mantine-react-table/ca.json
Labels: enhancement

#2289 fix: add error handling for available updates
  packages/api/src/router/update-checker.ts
Labels: bug

#2282 fix: add mysql pool with keep-alive to not close the connection
  packages/db/driver.ts
Labels: bug

#2321 feat(groups): add home board settings
  apps/nextjs/package.json
  apps/nextjs/src/app/[locale]/manage/settings/_components/board-settings-form.tsx
  apps/nextjs/src/app/[locale]/manage/users/[userId]/general/_components/_change-home-board.tsx
  apps/nextjs/src/app/[locale]/manage/users/[userId]/general/page.tsx
  apps/nextjs/src/app/[locale]/manage/users/groups/[id]/layout.tsx
  apps/nextjs/src/app/[locale]/manage/users/groups/[id]/settings/_group-home-boards.tsx
  apps/nextjs/src/app/[locale]/manage/users/groups/[id]/settings/page.tsx
  apps/nextjs/src/app/[locale]/manage/users/groups/_add-group.tsx
  apps/nextjs/src/app/[locale]/manage/users/groups/_client.tsx
  apps/nextjs/src/app/[locale]/manage/users/groups/_groups-table.tsx
  apps/nextjs/src/app/[locale]/manage/users/groups/groups.module.css
  apps/nextjs/src/app/[locale]/manage/users/groups/page.tsx
  apps/nextjs/src/components/board/board-select.tsx
  e2e/shared/actions/onboarding-actions.ts
  packages/api/src/router/board.ts
  packages/api/src/router/group.ts
  packages/api/src/router/test/board.spec.ts
  packages/api/src/router/test/group.spec.ts
  packages/api/src/router/user.ts
  packages/auth/permissions/test/integration-query-permissions.spec.ts
  packages/auth/providers/test/ldap-authorization.spec.ts
  packages/auth/test/callbacks.spec.ts
  packages/auth/test/events.spec.ts
  packages/db/migrations/mysql/0025_add-group-home-board-settings.sql
  packages/db/migrations/mysql/meta/0025_snapshot.json
  packages/db/migrations/mysql/meta/_journal.json
  packages/db/migrations/seed.ts
  packages/db/migrations/sqlite/0025_add-group-home-board-settings.sql
  packages/db/migrations/sqlite/meta/0025_snapshot.json
  packages/db/migrations/sqlite/meta/_journal.json
  packages/db/queries/group.ts
  packages/db/queries/index.ts
  packages/db/schema/mysql.ts
  packages/db/schema/sqlite.ts
  packages/old-import/src/import/collections/user-collection.ts
  packages/translation/src/lang/en.json
  packages/ui/src/components/index.tsx
  packages/ui/src/components/select-with-custom-items.tsx
  packages/validation/src/group.ts
  pnpm-lock.yaml
Labels: enhancement

#2328 fix: missing cover types media organizers
  packages/integrations/src/media-organizer/lidarr/lidarr-integration.ts
  packages/integrations/src/media-organizer/media-organizer-integration.ts
  packages/integrations/src/media-organizer/radarr/radarr-integration.ts
  packages/integrations/src/media-organizer/readarr/readarr-integration.ts
  packages/integrations/src/media-organizer/sonarr/sonarr-integration.ts
Labels: bug

#2329 feat: downgrade log level callback succeeded
  packages/common/src/stopwatch.ts
  packages/cron-jobs-core/src/creator.ts
  packages/cron-jobs-core/src/logger.ts
  packages/cron-jobs/src/jobs/icons-updater.ts
  packages/cron-jobs/src/lib/index.ts
Labels: enhancement

#2338 feat: add tile border radius
  apps/nextjs/src/app/[locale]/boards/[name]/settings/_appereance.tsx
  apps/nextjs/src/app/[locale]/boards/[name]/settings/page.tsx
  apps/nextjs/src/components/board/items/item-content.tsx
  apps/nextjs/src/components/board/sections/category-section.tsx
  apps/nextjs/src/components/board/sections/dynamic-section.tsx
  packages/api/src/router/board.ts
  packages/db/migrations/mysql/0026_add-border-radius.sql
  packages/db/migrations/mysql/meta/0026_snapshot.json
  packages/db/migrations/mysql/meta/_journal.json
  packages/db/migrations/sqlite/0026_add-border-radius.sql
  packages/db/migrations/sqlite/meta/0026_snapshot.json
  packages/db/migrations/sqlite/meta/_journal.json
  packages/db/package.json
  packages/db/schema/mysql.ts
  packages/db/schema/sqlite.ts
  packages/translation/src/lang/en.json
  packages/validation/src/board.ts
  pnpm-lock.yaml
Labels: enhancement

#2366 feat(cli): add fix-username command to make all usernames lowercase
  packages/cli/src/commands/fix-usernames.ts
  packages/cli/src/index.ts
Labels: enhancement

#2337 fix: omv integrations is unable to correctly retrieve the file system when using omv-zfs
  packages/integrations/src/openmediavault/openmediavault-integration.ts
  packages/integrations/src/openmediavault/openmediavault-types.ts
Labels: bug

#2228 feat(board): allow to set icon color of widgets
  apps/nextjs/src/app/[locale]/boards/(content)/_theme.tsx
  apps/nextjs/src/app/[locale]/boards/[name]/settings/_appereance.tsx
  packages/api/src/router/board.ts
  packages/db/migrations/mysql/0027_acoustic_karma.sql
  packages/db/migrations/mysql/meta/0027_snapshot.json
  packages/db/migrations/mysql/meta/_journal.json
  packages/db/migrations/sqlite/0027_wooden_blizzard.sql
  packages/db/migrations/sqlite/meta/0027_snapshot.json
  packages/db/migrations/sqlite/meta/_journal.json
  packages/db/schema/mysql.ts
  packages/db/schema/sqlite.ts
  packages/translation/src/lang/en.json
  packages/ui/src/components/index.tsx
  packages/ui/src/components/masked-image.module.css
  packages/ui/src/components/masked-image.tsx
  packages/ui/src/components/masked-or-normal-image.tsx
  packages/validation/src/board.ts
  packages/widgets/src/app/app.module.css
  packages/widgets/src/app/component.tsx
  packages/widgets/src/bookmarks/bookmark.module.css
  packages/widgets/src/bookmarks/component.tsx
  packages/widgets/src/dns-hole/controls/component.tsx
  pnpm-lock.yaml
Labels: enhancement

#2372 docs: Add links to all banners of readme
  docs/README.md
Labels: documentation

#2379 feat: redirect to login screen when no global home board
  apps/nextjs/src/app/[locale]/boards/_layout-creator.tsx
Labels: enhancement

#2381 fix(medias): svg files don't load in list
  apps/nextjs/src/app/[locale]/manage/medias/page.tsx
Labels: bug

#2390 fix(widgets): app icon not visible
  packages/widgets/src/app/app.module.css
Labels: bug

#2392 ci: fix rebase for dev not working on release
  .github/workflows/deployment-docker-image.yml
Labels: bug

#2380 feat: add app ping url
  packages/api/src/router/app.ts
  packages/api/src/router/test/app.spec.ts
  packages/db/migrations/mysql/0028_add_app_ping_url.sql
  packages/db/migrations/mysql/meta/0028_snapshot.json
  packages/db/migrations/mysql/meta/_journal.json
  packages/db/migrations/sqlite/0028_add_app_ping_url.sql
  packages/db/migrations/sqlite/meta/0028_snapshot.json
  packages/db/migrations/sqlite/meta/_journal.json
  packages/db/schema/mysql.ts
  packages/db/schema/sqlite.ts
  packages/forms-collection/src/new-app/_form.tsx
  packages/modals-collection/src/docker/add-docker-app-to-homarr.tsx
  packages/old-import/src/import-apps.ts
  packages/old-import/src/mappers/map-app.ts
  packages/translation/src/lang/en.json
  packages/validation/src/app.ts
  packages/widgets/src/app/component.tsx
  packages/widgets/src/bookmarks/add-button.tsx
Labels: enhancement

#2322 fix: omv invalid temperature when not available
  .run/typecheck.run.xml
  packages/integrations/src/interfaces/health-monitoring/healt-monitoring.ts
  packages/integrations/src/openmediavault/openmediavault-types.ts
  packages/widgets/src/health-monitoring/system-health.tsx
Labels: bug

#2402 fix: update checker logs incorrectly
  packages/request-handler/src/update-checker.ts
Labels: bug

#2409 fix(boards): add scrollarea to board-select
  apps/nextjs/src/app/[locale]/boards/(content)/_header-actions.tsx
Labels: bug

#2438 fix(deps): downgrade to next 15.1.7 cause of turbopack crash with 15.2.0 and above
  .github/renovate.json5
  apps/nextjs/package.json
  packages/api/package.json
  packages/auth/package.json
  packages/common/package.json
  packages/modals-collection/package.json
  packages/old-import/package.json
  packages/settings/package.json
  packages/spotlight/package.json
  packages/translation/package.json
  packages/ui/package.json
  packages/widgets/package.json
  pnpm-lock.yaml
  tooling/eslint/package.json
Labels: bug

#2440 fix: chinese traditional locale
  packages/translation/src/config.ts
  packages/translation/src/lang/tw.json
Labels: bug
